#!/usr/bin/env -S python3 -S -OO
from enum import StrEnum
from pathlib import PosixPath
from os import set_blocking


class ColourCodes(StrEnum):
    BLACK = "0m"
    WHITE = "15m"
    BLUE = "27m"
    TURQUOISE = "30m"
    GREEN = "34m"
    CYAN = "36m"
    LIGHT_BLUE = "39m"
    PALE_GREEN = "42m"
    STEEL_BLUE = "39m"
    PURPLE = "93m"
    RED = "124m"
    MAGENTA = "127m"
    BROWN = "138m"
    LIGHT_MAGENTA = "163m"
    DARK_ORANGE = "166m"
    ORANGE = "172m"
    YELLOW = "178m"
    LIGHT_RED = "196m"


class EscapeCodes(StrEnum):
    PREFIX = "\033["
    FOREGROUND = "38;"
    BACKGROUND = "48;"
    INFIX = "5;"
    PFI = f"{PREFIX}{FOREGROUND}{INFIX}"
    PBI = f"{PREFIX}{BACKGROUND}{INFIX}"


class Colours(StrEnum):
    NOCOLOUR = "\033[0m"
    BOLD = "\033[1m"
    UNDERLINE = "\033[4m"
    BLINK = "\033[5m"
    FSTEEL = f"{EscapeCodes.PFI}{ColourCodes.STEEL_BLUE}"
    BSTEEL = f"{EscapeCodes.PBI}{ColourCodes.STEEL_BLUE}"
    FBLUE = f"{EscapeCodes.PFI}{ColourCodes.BLUE}"
    BBLUE = f"{EscapeCodes.PBI}{ColourCodes.BLUE}"
    FCYAN = f"{EscapeCodes.PFI}{ColourCodes.CYAN}"
    BCYAN = f"{EscapeCodes.PBI}{ColourCodes.CYAN}"
    FTURQUOISE = f"{EscapeCodes.PFI}{ColourCodes.TURQUOISE}"
    BTURQUOISE = f"{EscapeCodes.PBI}{ColourCodes.TURQUOISE}"
    FLBLUE = f"{EscapeCodes.PFI}{ColourCodes.LIGHT_BLUE}"
    BLBLUE = f"{EscapeCodes.PBI}{ColourCodes.LIGHT_BLUE}"
    FGREEN = f"{EscapeCodes.PFI}{ColourCodes.GREEN}"
    BGREEN = f"{EscapeCodes.PBI}{ColourCodes.GREEN}"
    FPGREEN = f"{EscapeCodes.PFI}{ColourCodes.PALE_GREEN}"
    BPGREEN = f"{EscapeCodes.PBI}{ColourCodes.PALE_GREEN}"
    FMAGENTA = f"{EscapeCodes.PFI}{ColourCodes.MAGENTA}"
    BMAGENTA = f"{EscapeCodes.PBI}{ColourCodes.MAGENTA}"
    FLMAGENTA = f"{EscapeCodes.PFI}{ColourCodes.LIGHT_MAGENTA}"
    BLMAGENTA = f"{EscapeCodes.PBI}{ColourCodes.LIGHT_MAGENTA}"
    FYELLOW = f"{EscapeCodes.PFI}{ColourCodes.YELLOW}"
    BYELLOW = f"{EscapeCodes.PBI}{ColourCodes.YELLOW}"
    FRED = f"{EscapeCodes.PFI}{ColourCodes.RED}"
    BRED = f"{EscapeCodes.PBI}{ColourCodes.RED}"
    FLRED = f"{EscapeCodes.PFI}{ColourCodes.LIGHT_RED}"
    BLRED = f"{EscapeCodes.PBI}{ColourCodes.LIGHT_RED}"
    FBROWN = f"{EscapeCodes.PFI}{ColourCodes.BROWN}"
    BBROWN = f"{EscapeCodes.PBI}{ColourCodes.BROWN}"
    FPURPLE = f"{EscapeCodes.PFI}{ColourCodes.PURPLE}"
    BPURPLE = f"{EscapeCodes.PBI}{ColourCodes.PURPLE}"
    FORANGE = f"{EscapeCodes.PFI}{ColourCodes.ORANGE}"
    BORANGE = f"{EscapeCodes.PBI}{ColourCodes.ORANGE}"
    FDORANGE = f"{EscapeCodes.PFI}{ColourCodes.DARK_ORANGE}"
    BDORANGE = f"{EscapeCodes.PBI}{ColourCodes.DARK_ORANGE}"
    FWHITE = f"{EscapeCodes.PFI}{ColourCodes.WHITE}"
    BWHITE = f"{EscapeCodes.PBI}{ColourCodes.WHITE}"
    BBLACK = f"{EscapeCodes.PBI}{ColourCodes.BLACK}"
    FBLACK = f"{EscapeCodes.PFI}{ColourCodes.BLACK}"


def colour_string(text: str, colour: list[Colours: str]):
    return f"{''.join(colour)}{text}{Colours.NOCOLOUR}"


def root_modifier():
    return Colours.UNDERLINE


def block_modifier():
    return Colours.BOLD


def mount_modifier():
    return Colours.BLINK


def get_all_modifiers(p) -> list[Colours]:
    mods = []
    if p.owner() == "root":
        mods.append(root_modifier())

    if p.is_block_device():
        mods.append(block_modifier())

    if p.is_mount():
        mods.append(mount_modifier())

    return mods


def colour_default(p):
    modifiers = get_all_modifiers(p)

    if p.is_symlink():
        coloured_name = colour_string(p.name, modifiers + [Colours.BWHITE, Colours.FBLACK])
    else:
        coloured_name = colour_string(p.name, modifiers)

    return coloured_name


def colour_dir(p):
    modifiers = get_all_modifiers(p)

    try:
        if any(p.iterdir()):
            if p.is_symlink():
                coloured_name = colour_string(p.name, modifiers + [Colours.BBLUE, Colours.FWHITE])
            else:
                coloured_name = colour_string(p.name, modifiers + [Colours.FBLUE])
        else:
            if p.is_symlink():
                coloured_name = colour_string(p.name, modifiers + [Colours.BLBLUE, Colours.FWHITE])
            else:
                coloured_name = colour_string(p.name, modifiers + [Colours.FLBLUE])
    except PermissionError:
        return colour_default(p)

    return coloured_name


def colour_broken_symlink(p):
    coloured_name = colour_string(p.name, [Colours.BRED, Colours.FWHITE])

    return coloured_name


def colour_py(p):
    modifiers = get_all_modifiers(p)

    if p.is_symlink():
        coloured_name = colour_string(p.name, modifiers + [Colours.BYELLOW, Colours.FWHITE])
    else:
        coloured_name = colour_string(p.name, modifiers + [Colours.FYELLOW])

    return coloured_name


def colour_archive(p):
    modifiers = get_all_modifiers(p)

    if p.is_symlink():
        coloured_name = colour_string(p.name, modifiers + [Colours.BMAGENTA, Colours.FWHITE])
    else:
        coloured_name = colour_string(p.name, modifiers + [Colours.FMAGENTA])

    return coloured_name


def colour_bash(p):
    modifiers = get_all_modifiers(p)

    if p.is_symlink():
        coloured_name = colour_string(p.name, modifiers + [Colours.BPGREEN, Colours.FWHITE])
    else:
        coloured_name = colour_string(p.name, modifiers + [Colours.FPGREEN])

    return coloured_name


def colour_video(p):
    modifiers = get_all_modifiers(p)

    if p.is_symlink():
        coloured_name = colour_string(p.name, modifiers + [Colours.BORANGE, Colours.FWHITE])
    else:
        coloured_name = colour_string(p.name, modifiers + [Colours.FORANGE])

    return coloured_name


def colour_audio(p):
    modifiers = get_all_modifiers(p)

    if p.is_symlink():
        coloured_name = colour_string(p.name, modifiers + [Colours.BPURPLE, Colours.FWHITE])
    else:
        coloured_name = colour_string(p.name, modifiers + [Colours.FPURPLE])

    return coloured_name


def colour_config(p):
    modifiers = get_all_modifiers(p)

    if p.is_symlink():
        coloured_name = colour_string(p.name, modifiers + [Colours.BCYAN, Colours.FWHITE])
    else:
        coloured_name = colour_string(p.name, modifiers + [Colours.FCYAN])

    return coloured_name


def colour_virt(p):
    modifiers = get_all_modifiers(p)

    if p.is_symlink():
        coloured_name = colour_string(p.name, modifiers + [Colours.BSTEEL, Colours.FWHITE])
    else:
        coloured_name = colour_string(p.name, modifiers + [Colours.FSTEEL])

    return coloured_name


def colour(p: PosixPath):
    if p.is_dir():
        return colour_dir(p)

    try:
        extl = p.name.split(".")[1:]
        ext = ".".join(extl)
        return __extension_colours[ext](p)
    except KeyError:
        pass

    try:
        with open(p, "r", encoding="utf-8") as f:
            set_blocking(f.fileno(), False)
            head = f.readline(__shebang_max_length)
        return __shebang_colours[head](p)
    except FileNotFoundError:
        return colour_broken_symlink(p)
    except KeyError:
        # couldn't find the appropriate shebang
        pass
    except OSError:
        # generic error; could be permission issues or a trillion other things
        pass
    except UnicodeError:
        pass

    return colour_default(p)


__extension_colours = {
    "py": colour_py,
    "pyc": colour_py,
    "pyo": colour_py,
    "pyd": colour_py,
    "sh": colour_bash,
    "521": colour_config,
    "abs": colour_config,
    "adb": colour_config,
    "adba": colour_config,
    "ae0": colour_config,
    "ams": colour_config,
    "api": colour_config,
    "apm": colour_config,
    "asgp": colour_config,
    "autoconf": colour_config,
    "avastconfig": colour_config,
    "avgconfig": colour_config,
    "axc": colour_config,
    "bfd": colour_config,
    "bgi": colour_config,
    "bitcfg": colour_config,
    "bitpim": colour_config,
    "bochsrc": colour_config,
    "bootstrap": colour_config,
    "brg": colour_config,
    "bsi": colour_config,
    "bsl": colour_config,
    "btf": colour_config,
    "bus": colour_config,
    "bwz": colour_config,
    "bxrc": colour_config,
    "c": colour_config,
    "ccb": colour_config,
    "ccf": colour_config,
    "ccfg": colour_config,
    "cch": colour_config,
    "ccr": colour_config,
    "cdd": colour_config,
    "ced": colour_config,
    "ceid": colour_config,
    "cekey": colour_config,
    "cezeokey": colour_config,
    "cf": colour_config,
    "cf3": colour_config,
    "cfg": colour_config,
    "cfs": colour_config,
    "cgi": colour_config,
    "ch": colour_config,
    "cha": colour_config,
    "chat": colour_config,
    "chf": colour_config,
    "cld": colour_config,
    "cm": colour_config,
    "cmate": colour_config,
    "cnf": colour_config,
    "cnn": colour_config,
    "color": colour_config,
    "con": colour_config,
    "conf": colour_config,
    "conf-auto": colour_config,
    "config": colour_config,
    "cos": colour_config,
    "cq": colour_config,
    "crp": colour_config,
    "cscfg": colour_config,
    "csd": colour_config,
    "csr": colour_config,
    "ctr": colour_config,
    "cwc": colour_config,
    "cwy": colour_config,
    "dbc": colour_config,
    "dcb": colour_config,
    "dcc": colour_config,
    "dcf": colour_config,
    "dcfg": colour_config,
    "ddt": colour_config,
    "devicemetadata-ms": colour_config,
    "dfc": colour_config,
    "diagcfg": colour_config,
    "dks": colour_config,
    "dmc": colour_config,
    "dno": colour_config,
    "dockerignore": colour_config,
    "drh": colour_config,
    "dtpc": colour_config,
    "dtsconfig": colour_config,
    "dtsearch": colour_config,
    "dvp": colour_config,
    "dyc": colour_config,
    "ecf": colour_config,
    "ecu": colour_config,
    "efc": colour_config,
    "eg2": colour_config,
    "ehi": colour_config,
    "elc": colour_config,
    "emv": colour_config,
    "epf": colour_config,
    "eqconfig": colour_config,
    "esi": colour_config,
    "esp": colour_config,
    "evp": colour_config,
    "ewc": colour_config,
    "exe4j": colour_config,
    "exprwdconfig": colour_config,
    "ezc": colour_config,
    "ezhex": colour_config,
    "fbk": colour_config,
    "fdp": colour_config,
    "ffs_batch": colour_config,
    "ffs_gui": colour_config,
    "ffs_real": colour_config,
    "fhx": colour_config,
    "fig": colour_config,
    "fpw": colour_config,
    "fsi": colour_config,
    "fst": colour_config,
    "ftp": colour_config,
    "ftpconfig": colour_config,
    "fwt": colour_config,
    "fxc": colour_config,
    "g16": colour_config,
    "gdm": colour_config,
    "gdt": colour_config,
    "gen": colour_config,
    "geo": colour_config,
    "ghi": colour_config,
    "gitconfig": colour_config,
    "gladinetsp": colour_config,
    "global": colour_config,
    "gml": colour_config,
    "god": colour_config,
    "grd": colour_config,
    "gsd": colour_config,
    "hcfg": colour_config,
    "hcm": colour_config,
    "hcr": colour_config,
    "hcu": colour_config,
    "helpcfg": colour_config,
    "hexdwc": colour_config,
    "hfc": colour_config,
    "hfmx": colour_config,
    "hid": colour_config,
    "htaccess": colour_config,
    "iaf": colour_config,
    "ica": colour_config,
    "icte": colour_config,
    "ifb": colour_config,
    "igd": colour_config,
    "iip": colour_config,
    "ini2": colour_config,
    "inuse": colour_config,
    "inz": colour_config,
    "iok": colour_config,
    "iom": colour_config,
    "irafhosts": colour_config,
    "isc": colour_config,
    "iuux": colour_config,
    "ivc": colour_config,
    "jcf": colour_config,
    "jic": colour_config,
    "jkm": colour_config,
    "joy": colour_config,
    "jtg": colour_config,
    "jvr": colour_config,
    "kcf": colour_config,
    "keyboard": colour_config,
    "kgr": colour_config,
    "ktw": colour_config,
    "launch": colour_config,
    "lcc": colour_config,
    "lct": colour_config,
    "ld": colour_config,
    "leases": colour_config,
    "les": colour_config,
    "llp": colour_config,
    "lnt": colour_config,
    "lpd": colour_config,
    "lvt": colour_config,
    "magic": colour_config,
    "mbc": colour_config,
    "mcc": colour_config,
    "mcd": colour_config,
    "mcs": colour_config,
    "mcserver": colour_config,
    "mdrc": colour_config,
    "me": colour_config,
    "met": colour_config,
    "mew": colour_config,
    "mhc": colour_config,
    "mky": colour_config,
    "mm3": colour_config,
    "mm4": colour_config,
    "mmf": colour_config,
    "mmrc": colour_config,
    "mozconfig": colour_config,
    "mpa": colour_config,
    "mspl": colour_config,
    "mxd": colour_config,
    "mxu": colour_config,
    "nba": colour_config,
    "nbo": colour_config,
    "ncc": colour_config,
    "ncf": colour_config,
    "ncfg": colour_config,
    "nck": colour_config,
    "ncm": colour_config,
    "ne0": colour_config,
    "net": colour_config,
    "netsh": colour_config,
    "nfg": colour_config,
    "nns": colour_config,
    "nsd": colour_config,
    "nsu": colour_config,
    "olsr": colour_config,
    "opf": colour_config,
    "opt": colour_config,
    "options": colour_config,
    "opts": colour_config,
    "ora": colour_config,
    "osd": colour_config,
    "ovpn": colour_config,
    "p9d": colour_config,
    "par": colour_config,
    "parm": colour_config,
    "pat": colour_config,
    "pb": colour_config,
    "pb1": colour_config,
    "pb2": colour_config,
    "pc2": colour_config,
    "pc3": colour_config,
    "pcf": colour_config,
    "pcp": colour_config,
    "pdk": colour_config,
    "perfmoncfg": colour_config,
    "perlcriticrc": colour_config,
    "pfg": colour_config,
    "phl": colour_config,
    "pln": colour_config,
    "pltcfg": colour_config,
    "pnagent": colour_config,
    "pnc": colour_config,
    "prb": colour_config,
    "prm": colour_config,
    "pro": colour_config,
    "profiles": colour_config,
    "properties": colour_config,
    "proxy": colour_config,
    "prp": colour_config,
    "prt": colour_config,
    "ps1xml": colour_config,
    "psrc": colour_config,
    "ptg": colour_config,
    "pth": colour_config,
    "pti": colour_config,
    "pui": colour_config,
    "pvx": colour_config,
    "pwr": colour_config,
    "pxc": colour_config,
    "pxg": colour_config,
    "qdr": colour_config,
    "qwc": colour_config,
    "rak": colour_config,
    "rap": colour_config,
    "rb": colour_config,
    "rc": colour_config,
    "rcf": colour_config,
    "rdg": colour_config,
    "resourceconfig": colour_config,
    "rsp": colour_config,
    "rsx": colour_config,
    "rta": colour_config,
    "sch": colour_config,
    "sconscript": colour_config,
    "scp": colour_config,
    "scpcfg": colour_config,
    "sdc": colour_config,
    "sdg": colour_config,
    "set": colour_config,
    "settingcontent-ms": colour_config,
    "sgc": colour_config,
    "siz": colour_config,
    "soc": colour_config,
    "spd": colour_config,
    "spdesignconfig": colour_config,
    "srf": colour_config,
    "srv": colour_config,
    "status": colour_config,
    "sublime-workspace": colour_config,
    "sup": colour_config,
    "svy": colour_config,
    "sxc": colour_config,
    "sxcu": colour_config,
    "sxp": colour_config,
    "sydx": colour_config,
    "t4": colour_config,
    "tbr": colour_config,
    "tc": colour_config,
    "td": colour_config,
    "td2": colour_config,
    "tds": colour_config,
    "tdw": colour_config,
    "tf": colour_config,
    "tfa": colour_config,
    "tgb": colour_config,
    "tim": colour_config,
    "tll": colour_config,
    "tm": colour_config,
    "tmap": colour_config,
    "top": colour_config,
    "tsm": colour_config,
    "tvc": colour_config,
    "twc": colour_config,
    "txm": colour_config,
    "uae": colour_config,
    "ubb": colour_config,
    "ubr": colour_config,
    "ucf": colour_config,
    "und": colour_config,
    "uvoptx": colour_config,
    "vcf": colour_config,
    "vcl": colour_config,
    "bashrc": colour_config,
    "vimrc": colour_config,
    "vis": colour_config,
    "vmc": colour_config,
    "vpn": colour_config,
    "vrf": colour_config,
    "vsc": colour_config,
    "vsh": colour_config,
    "vue": colour_config,
    "vv": colour_config,
    "vvi": colour_config,
    "wadcfg": colour_config,
    "wbx": colour_config,
    "wcf": colour_config,
    "wcr": colour_config,
    "wda": colour_config,
    "wed": colour_config,
    "wlm": colour_config,
    "wsb": colour_config,
    "wsp": colour_config,
    "wti": colour_config,
    "wxa": colour_config,
    "wys": colour_config,
    "x4k": colour_config,
    "xcpad": colour_config,
    "xdfl": colour_config,
    "xilize": colour_config,
    "xmc": colour_config,
    "xnp": colour_config,
    "xpl": colour_config,
    "yaml": colour_config,
    "ypf": colour_config,
    "yt": colour_config,
    "zc": colour_config,
    "zcc": colour_config,
    "zcfg": colour_config,
    "zup": colour_config,
    "zzb": colour_config,
    "zzc": colour_config,
    "zzd": colour_config,
    "zze": colour_config,
    "zzf": colour_config,
    "zzk": colour_config,
    "zzp": colour_config,
    "zzt": colour_config,
    "_02": colour_audio,
    "10": colour_audio,
    "16": colour_audio,
    "2": colour_audio,
    "2ch": colour_audio,
    "3ga": colour_audio,
    "7": colour_audio,
    "8svx": colour_audio,
    "aa3": colour_audio,
    "aaf": colour_audio,
    "aax": colour_audio,
    "abc": colour_audio,
    "abk": colour_audio,
    "abm": colour_audio,
    "ac7": colour_audio,
    "acd": colour_audio,
    "acid": colour_audio,
    "acm": colour_audio,
    "ad2": colour_audio,
    "ad3": colour_audio,
    "ad4": colour_audio,
    "adg": colour_audio,
    "adts": colour_audio,
    "afs": colour_audio,
    "ahx": colour_audio,
    "ajp": colour_audio,
    "alb": colour_audio,
    "alc": colour_audio,
    "als": colour_audio,
    "amxd": colour_audio,
    "amz": colour_audio,
    "ang": colour_audio,
    "aob": colour_audio,
    "ap4": colour_audio,
    "architect": colour_audio,
    "arf": colour_audio,
    "aria": colour_audio,
    "atp": colour_audio,
    "aud": colour_audio,
    "audio": colour_audio,
    "audionote": colour_audio,
    "aupreset": colour_audio,
    "ay": colour_audio,
    "azx": colour_audio,
    "bmu": colour_audio,
    "bmw": colour_audio,
    "bnk": colour_audio,
    "br25": colour_audio,
    "br27": colour_audio,
    "br28": colour_audio,
    "br29": colour_audio,
    "br4": colour_audio,
    "br5": colour_audio,
    "brr": colour_audio,
    "bvf": colour_audio,
    "bww": colour_audio,
    "camelsounds": colour_audio,
    "cdg": colour_audio,
    "cdo": colour_audio,
    "ckb": colour_audio,
    "ckf": colour_audio,
    "cmo": colour_audio,
    "cs3": colour_audio,
    "cvs": colour_audio,
    "cwb": colour_audio,
    "cwp": colour_audio,
    "dat": colour_audio,
    "dau": colour_audio,
    "dig": colour_audio,
    "dkd": colour_audio,
    "dm1": colour_audio,
    "dmkit": colour_audio,
    "dmpatch": colour_audio,
    "dmptrn": colour_audio,
    "dmse": colour_audio,
    "dpdoc": colour_audio,
    "dra": colour_audio,
    "drx": colour_audio,
    "ds2": colour_audio,
    "dsd": colour_audio,
    "dsf": colour_audio,
    "dss": colour_audio,
    "dtm": colour_audio,
    "dtshd": colour_audio,
    "dva": colour_audio,
    "dvc": colour_audio,
    "dvf": colour_audio,
    "dvw": colour_audio,
    "dwp": colour_audio,
    "e2ev": colour_audio,
    "ea": colour_audio,
    "eac3": colour_audio,
    "elastik": colour_audio,
    "elp": colour_audio,
    "eol": colour_audio,
    "eop": colour_audio,
    "es": colour_audio,
    "esu": colour_audio,
    "evx": colour_audio,
    "exb": colour_audio,
    "fc4": colour_audio,
    "flm": colour_audio,
    "fnf": colour_audio,
    "ftc": colour_audio,
    "gbs": colour_audio,
    "gm": colour_audio,
    "gog": colour_audio,
    "gpbank": colour_audio,
    "gpx": colour_audio,
    "gtp": colour_audio,
    "h2p": colour_audio,
    "h2song": colour_audio,
    "hh": colour_audio,
    "hma": colour_audio,
    "hsb": colour_audio,
    "i3pack": colour_audio,
    "isb": colour_audio,
    "itz": colour_audio,
    "kam": colour_audio,
    "kar": colour_audio,
    "kfn": colour_audio,
    "kin": colour_audio,
    "kma": colour_audio,
    "koz": colour_audio,
    "krx": colour_audio,
    "la": colour_audio,
    "lme": colour_audio,
    "lms": colour_audio,
    "logicx": colour_audio,
    "lvp": colour_audio,
    "ly": colour_audio,
    "m2s": colour_audio,
    "m3a": colour_audio,
    "m3v": colour_audio,
    "mct": colour_audio,
    "mes": colour_audio,
    "mf3": colour_audio,
    "mfb": colour_audio,
    "mff": colour_audio,
    "mg2": colour_audio,
    "mgb": colour_audio,
    "mgu": colour_audio,
    "mia": colour_audio,
    "minibank": colour_audio,
    "mk1": colour_audio,
    "mkf": colour_audio,
    "mmjproject": colour_audio,
    "mmm": colour_audio,
    "mmpz": colour_audio,
    "mo3": colour_audio,
    "mogg": colour_audio,
    "moi": colour_audio,
    "mp_": colour_audio,
    "mp3": colour_audio,
    "mp3a": colour_audio,
    "mp3g": colour_audio,
    "mpc": colour_audio,
    "mpdp": colour_audio,
    "mscx": colour_audio,
    "mscz": colour_audio,
    "msv": colour_audio,
    "mt_": colour_audio,
    "mtd": colour_audio,
    "muk": colour_audio,
    "mus": colour_audio,
    "musx": colour_audio,
    "mv3": colour_audio,
    "mwk": colour_audio,
    "mww": colour_audio,
    "mx1": colour_audio,
    "mx4": colour_audio,
    "mx5": colour_audio,
    "mx6": colour_audio,
    "mxl": colour_audio,
    "my": colour_audio,
    "myr": colour_audio,
    "mz": colour_audio,
    "n3a": colour_audio,
    "nak": colour_audio,
    "nbkt": colour_audio,
    "nbs": colour_audio,
    "nfm8": colour_audio,
    "ngrr": colour_audio,
    "niff": colour_audio,
    "nki": colour_audio,
    "nmf": colour_audio,
    "nmsv": colour_audio,
    "npr": colour_audio,
    "nsla": colour_audio,
    "nsmp": colour_audio,
    "nsp": colour_audio,
    "nst": colour_audio,
    "nwp": colour_audio,
    "nxt": colour_audio,
    "ocdf": colour_audio,
    "odd": colour_audio,
    "oga": colour_audio,
    "oma": colour_audio,
    "omf": colour_audio,
    "omx": colour_audio,
    "opus": colour_audio,
    "ove": colour_audio,
    "oxm": colour_audio,
    "pc": colour_audio,
    "pcm": colour_audio,
    "plp": colour_audio,
    "pno": colour_audio,
    "psi": colour_audio,
    "ptb": colour_audio,
    "pttune": colour_audio,
    "ptx": colour_audio,
    "puma": colour_audio,
    "pw3": colour_audio,
    "qcp": colour_audio,
    "rcp": colour_audio,
    "rec": colour_audio,
    "record": colour_audio,
    "rex": colour_audio,
    "rf64": colour_audio,
    "rfl": colour_audio,
    "rgp": colour_audio,
    "rhl": colour_audio,
    "rhp": colour_audio,
    "rip": colour_audio,
    "rns": colour_audio,
    "rpp": colour_audio,
    "rsf": colour_audio,
    "rsn": colour_audio,
    "rso": colour_audio,
    "rtm": colour_audio,
    "rx2": colour_audio,
    "s48": colour_audio,
    "sa1": colour_audio,
    "sabl": colour_audio,
    "sabs": colour_audio,
    "sag": colour_audio,
    "sbg": colour_audio,
    "sbm": colour_audio,
    "sd2f": colour_audio,
    "sdat": colour_audio,
    "sesx": colour_audio,
    "sfz": colour_audio,
    "sg2": colour_audio,
    "sg4": colour_audio,
    "sgu": colour_audio,
    "sgw": colour_audio,
    "sib": colour_audio,
    "slx": colour_audio,
    "smf": colour_audio,
    "smfmf": colour_audio,
    "smp": colour_audio,
    "sn": colour_audio,
    "snd": colour_audio,
    "sng": colour_audio,
    "song": colour_audio,
    "sqt": colour_audio,
    "sri": colour_audio,
    "ssdl": colour_audio,
    "st3": colour_audio,
    "stem": colour_audio,
    "stem.mp4": colour_audio,
    "svd": colour_audio,
    "svq": colour_audio,
    "swa": colour_audio,
    "swv": colour_audio,
    "tak": colour_audio,
    "thd": colour_audio,
    "tks": colour_audio,
    "tl": colour_audio,
    "tn7": colour_audio,
    "tqd": colour_audio,
    "trm": colour_audio,
    "tsh": colour_audio,
    "tsl": colour_audio,
    "uvd": colour_audio,
    "uvn": colour_audio,
    "v8": colour_audio,
    "vbk": colour_audio,
    "vdj": colour_audio,
    "vdjsample": colour_audio,
    "vgm": colour_audio,
    "vif": colour_audio,
    "vig": colour_audio,
    "vm": colour_audio,
    "vmo": colour_audio,
    "vox": colour_audio,
    "voxal": colour_audio,
    "vsi": colour_audio,
    "vsq": colour_audio,
    "vsqx": colour_audio,
    "vst": colour_audio,
    "vy3": colour_audio,
    "vy4": colour_audio,
    "vyf": colour_audio,
    "w01": colour_audio,
    "w02": colour_audio,
    "w03": colour_audio,
    "w06": colour_audio,
    "w07": colour_audio,
    "waptt": colour_audio,
    "wave": colour_audio,
    "weba": colour_audio,
    "wem": colour_audio,
    "wpp": colour_audio,
    "wrf": colour_audio,
    "wrk": colour_audio,
    "wsx": colour_audio,
    "wv": colour_audio,
    "x3a": colour_audio,
    "x3v": colour_audio,
    "xkr": colour_audio,
    "xmz": colour_audio,
    "xpak": colour_audio,
    "xpf": colour_audio,
    "xsb": colour_audio,
    "xt": colour_audio,
    "xvag": colour_audio,
    "xwb": colour_audio,
    "xwma": colour_audio,
    "ym": colour_audio,
    "ytif": colour_audio,
    "zab": colour_audio,
    "zaf": colour_audio,
    "zax": colour_audio,
    "zik": colour_audio,
    "zvr": colour_audio,
    "avi": colour_video,
    "261": colour_video,
    "263": colour_video,
    "265": colour_video,
    "3gp_128x96": colour_video,
    "44": colour_video,
    "4xm": colour_video,
    "603": colour_video,
    "60d": colour_video,
    "800": colour_video,
    "890": colour_video,
    "aec": colour_video,
    "am2": colour_video,
    "am7": colour_video,
    "amc": colour_video,
    "amv": colour_video,
    "anydesk": colour_video,
    "apz": colour_video,
    "aqt": colour_video,
    "arcut": colour_video,
    "asdvdcrtproj": colour_video,
    "aut": colour_video,
    "avd": colour_video,
    "avf": colour_video,
    "avh": colour_video,
    "avr": colour_video,
    "axm": colour_video,
    "bay": colour_video,
    "bbv": colour_video,
    "bdav": colour_video,
    "bdmv": colour_video,
    "bdtp": colour_video,
    "bix": colour_video,
    "biz": colour_video,
    "bs4": colour_video,
    "bu": colour_video,
    "bub": colour_video,
    "buy": colour_video,
    "bvr": colour_video,
    "cak": colour_video,
    "cam": colour_video,
    "camproj": colour_video,
    "camrec": colour_video,
    "cine": colour_video,
    "clk": colour_video,
    "cpk": colour_video,
    "cpvc": colour_video,
    "crec": colour_video,
    "crv": colour_video,
    "cvc": colour_video,
    "cx3": colour_video,
    "d2v": colour_video,
    "dash": colour_video,
    "dav": colour_video,
    "dc8": colour_video,
    "dce": colour_video,
    "dcr": colour_video,
    "demo": colour_video,
    "demo4": colour_video,
    "dfxp": colour_video,
    "dgw": colour_video,
    "djanimations": colour_video,
    "dmsd": colour_video,
    "dmsm": colour_video,
    "dmss": colour_video,
    "dmx": colour_video,
    "dof": colour_video,
    "doink-gs": colour_video,
    "dpg": colour_video,
    "drc": colour_video,
    "dscf": colour_video,
    "dsm": colour_video,
    "dtcp-ip": colour_video,
    "dtv": colour_video,
    "dv4": colour_video,
    "dv5": colour_video,
    "dv-avi": colour_video,
    "dvddata": colour_video,
    "dvdmedia": colour_video,
    "dvdrip": colour_video,
    "dvm": colour_video,
    "dvt": colour_video,
    "dvx": colour_video,
    "dwz": colour_video,
    "dxa": colour_video,
    "el8": colour_video,
    "encm": colour_video,
    "epj": colour_video,
    "epm": colour_video,
    "es3": colour_video,
    "eti": colour_video,
    "etrg": colour_video,
    "ev2": colour_video,
    "eva": colour_video,
    "evo": colour_video,
    "exo": colour_video,
    "eye": colour_video,
    "ezp": colour_video,
    "eztv": colour_video,
    "fbr": colour_video,
    "fcp": colour_video,
    "fcpxml": colour_video,
    "film": colour_video,
    "flc": colour_video,
    "flexolibrary": colour_video,
    "flh": colour_video,
    "fli": colour_video,
    "fli_": colour_video,
    "flux": colour_video,
    "flvat": colour_video,
    "fm2": colour_video,
    "fmv": colour_video,
    "fsv": colour_video,
    "ftvx": colour_video,
    "fvt": colour_video,
    "g2m": colour_video,
    "g64": colour_video,
    "g64x": colour_video,
    "gfp": colour_video,
    "gifv": colour_video,
    "gir": colour_video,
    "gmm": colour_video,
    "grasp": colour_video,
    "gts": colour_video,
    "gvi": colour_video,
    "gxf": colour_video,
    "h260": colour_video,
    "h263": colour_video,
    "h265": colour_video,
    "h3r": colour_video,
    "h4v": colour_video,
    "h64": colour_video,
    "hav": colour_video,
    "hbox": colour_video,
    "hevc": colour_video,
    "hgd": colour_video,
    "hkv": colour_video,
    "hls": colour_video,
    "hlv": colour_video,
    "hmt": colour_video,
    "hmv": colour_video,
    "hnm": colour_video,
    "hq": colour_video,
    "htd": colour_video,
    "htp": colour_video,
    "hup": colour_video,
    "hvc1": colour_video,
    "ifv": colour_video,
    "iis": colour_video,
    "ilm": colour_video,
    "imovietrailer": colour_video,
    "irf": colour_video,
    "ismv": colour_video,
    "iva": colour_video,
    "ivf": colour_video,
    "ivm": colour_video,
    "ivs": colour_video,
    "jmf": colour_video,
    "jmm": colour_video,
    "jpv": colour_video,
    "jts": colour_video,
    "jyk": colour_video,
    "k3g": colour_video,
    "kava": colour_video,
    "kmv": colour_video,
    "kux": colour_video,
    "l3": colour_video,
    "l32": colour_video,
    "lrec": colour_video,
    "lrv": colour_video,
    "lsproj": colour_video,
    "lsx": colour_video,
    "lza": colour_video,
    "m1s": colour_video,
    "m21": colour_video,
    "m4f": colour_video,
    "m4s": colour_video,
    "m65": colour_video,
    "mbv": colour_video,
    "mcf": colour_video,
    "mcv": colour_video,
    "mep": colour_video,
    "mepx": colour_video,
    "mgv": colour_video,
    "mhg": colour_video,
    "mio": colour_video,
    "mj2": colour_video,
    "mjp": colour_video,
    "mjp2": colour_video,
    "m-jpeg": colour_video,
    "mjpeg": colour_video,
    "mjpg": colour_video,
    "ml20": colour_video,
    "mmp": colour_video,
    "moff": colour_video,
    "mp4": colour_video,
    "mp4v": colour_video,
    "mp4;v=1": colour_video,
    "mp7": colour_video,
    "mpeg1": colour_video,
    "mpeg2": colour_video,
    "mpeg4": colour_video,
    "mpegps": colour_video,
    "mpg2": colour_video,
    "mpgv": colour_video,
    "mpgx": colour_video,
    "mpj": colour_video,
    "mps": colour_video,
    "mqv": colour_video,
    "mts1": colour_video,
    "mtv": colour_video,
    "mv": colour_video,
    "mv1": colour_video,
    "mv2": colour_video,
    "mvc": colour_video,
    "mvd": colour_video,
    "mvf": colour_video,
    "mvr": colour_video,
    "mvv": colour_video,
    "mvy": colour_video,
    "mxv": colour_video,
    "mkv": colour_video,
    "n3r": colour_video,
    "nde": colour_video,
    "nfv": colour_video,
    "nmm": colour_video,
    "noa": colour_video,
    "npv": colour_video,
    "nvc": colour_video,
    "nvl": colour_video,
    "nxv": colour_video,
    "ogx": colour_video,
    "osp": colour_video,
    "otrkey": colour_video,
    "p2": colour_video,
    "pds": colour_video,
    "pgmx": colour_video,
    "pmp": colour_video,
    "ppp": colour_video,
    "pproj": colour_video,
    "ps": colour_video,
    "pvr": colour_video,
    "px": colour_video,
    "pxm": colour_video,
    "pxv": colour_video,
    "pyv": colour_video,
    "pz": colour_video,
    "qcif": colour_video,
    "qmx": colour_video,
    "qtm": colour_video,
    "qvt": colour_video,
    "r3d": colour_video,
    "rargb": colour_video,
    "ratDVD": colour_video,
    "ravi": colour_video,
    "rca": colour_video,
    "rcrec": colour_video,
    "rdt": colour_video,
    "rec_part0": colour_video,
    "rec_part1": colour_video,
    "rec_part2": colour_video,
    "rec_part3": colour_video,
    "rki": colour_video,
    "rmhd": colour_video,
    "roq": colour_video,
    "rpl": colour_video,
    "rt4": colour_video,
    "rtv": colour_video,
    "rum": colour_video,
    "rvl": colour_video,
    "s11": colour_video,
    "s2e": colour_video,
    "s4ud": colour_video,
    "san": colour_video,
    "sbs": colour_video,
    "scc": colour_video,
    "scm": colour_video,
    "scn": colour_video,
    "scr": colour_video,
    "screenrec": colour_video,
    "sdr2": colour_video,
    "sdv": colour_video,
    "seq": colour_video,
    "siv": colour_video,
    "slc": colour_video,
    "smv": colour_video,
    "splash": colour_video,
    "sqz": colour_video,
    "ssif": colour_video,
    "ssw": colour_video,
    "st4": colour_video,
    "stj": colour_video,
    "stk": colour_video,
    "strg": colour_video,
    "stu": colour_video,
    "svcd": colour_video,
    "svi": colour_video,
    "swi": colour_video,
    "tdt2": colour_video,
    "tgv": colour_video,
    "theater": colour_video,
    "tivo": colour_video,
    "tmi": colour_video,
    "tms": colour_video,
    "tp0": colour_video,
    "trec": colour_video,
    "tridefmovie": colour_video,
    "trn": colour_video,
    "ts4": colour_video,
    "tscproj": colour_video,
    "tsp": colour_video,
    "tts": colour_video,
    "tv": colour_video,
    "tvs": colour_video,
    "tvv": colour_video,
    "ty": colour_video,
    "ub1": colour_video,
    "um4": colour_video,
    "urc": colour_video,
    "usm": colour_video,
    "uvs": colour_video,
    "v264": colour_video,
    "vc1": colour_video,
    "vcd": colour_video,
    "vcm": colour_video,
    "vcpf": colour_video,
    "vcr": colour_video,
    "vcv": colour_video,
    "vdr": colour_video,
    "veg": colour_video,
    "vep": colour_video,
    "vep4": colour_video,
    "vf": colour_video,
    "vfo": colour_video,
    "vg": colour_video,
    "vg2": colour_video,
    "vghd": colour_video,
    "vgx": colour_video,
    "vgz": colour_video,
    "vid": colour_video,
    "video": colour_video,
    "viewlet": colour_video,
    "vmlf": colour_video,
    "vmm": colour_video,
    "vod": colour_video,
    "vp3": colour_video,
    "vp6": colour_video,
    "vp7": colour_video,
    "vp8": colour_video,
    "vp9": colour_video,
    "vpd": colour_video,
    "vpg": colour_video,
    "vpj": colour_video,
    "vprj": colour_video,
    "vproj": colour_video,
    "vs2": colour_video,
    "vs4": colour_video,
    "vse": colour_video,
    "vvf": colour_video,
    "w32": colour_video,
    "w3d": colour_video,
    "wfp": colour_video,
    "wfsp": colour_video,
    "wm3": colour_video,
    "wmv3": colour_video,
    "wsve": colour_video,
    "wve": colour_video,
    "webm": colour_video,
    "xba": colour_video,
    "xlmv": colour_video,
    "xmm": colour_video,
    "xmv": colour_video,
    "xpv": colour_video,
    "xtodvd": colour_video,
    "xvw": colour_video,
    "y4m": colour_video,
    "yify": colour_video,
    "yts": colour_video,
    "zeg": colour_video,
    "7z": colour_archive,
    "7-zip": colour_archive,
    "7zip": colour_archive,
    "a20": colour_archive,
    "aar": colour_archive,
    "abbu": colour_archive,
    "ace": colour_archive,
    "adf": colour_archive,
    "afa": colour_archive,
    "air": colour_archive,
    "akp": colour_archive,
    "alz": colour_archive,
    "ap": colour_archive,
    "apple": colour_archive,
    "appv": colour_archive,
    "appxbundle": colour_archive,
    "arc": colour_archive,
    "arch00": colour_archive,
    "arj": colour_archive,
    "ark": colour_archive,
    "as4a": colour_archive,
    "asd": colour_archive,
    "asec": colour_archive,
    "atr": colour_archive,
    "axr": colour_archive,
    "b1": colour_archive,
    "b64": colour_archive,
    "ba": colour_archive,
    "bag": colour_archive,
    "bar": colour_archive,
    "bba": colour_archive,
    "bcz": colour_archive,
    "bee": colour_archive,
    "bel": colour_archive,
    "bh": colour_archive,
    "bin": colour_archive,
    "blb": colour_archive,
    "bma": colour_archive,
    "bnd": colour_archive,
    "boe": colour_archive,
    "boo": colour_archive,
    "btc": colour_archive,
    "bun": colour_archive,
    "bvx": colour_archive,
    "bz": colour_archive,
    "bz2": colour_archive,
    "ca1": colour_archive,
    "cab": colour_archive,
    "car": colour_archive,
    "carb": colour_archive,
    "caz": colour_archive,
    "cb7": colour_archive,
    "cbr": colour_archive,
    "cbt": colour_archive,
    "cbv": colour_archive,
    "cbz": colour_archive,
    "ccn": colour_archive,
    "cdoc": colour_archive,
    "cmp": colour_archive,
    "cpgz": colour_archive,
    "cpio": colour_archive,
    "cpt": colour_archive,
    "crf": colour_archive,
    "csk": colour_archive,
    "cso": colour_archive,
    "ctp": colour_archive,
    "cv": colour_archive,
    "czip": colour_archive,
    "dak": colour_archive,
    "dar": colour_archive,
    "dax": colour_archive,
    "dbz": colour_archive,
    "dd": colour_archive,
    "deb": colour_archive,
    "desktop": colour_archive,
    "devpak": colour_archive,
    "dfl": colour_archive,
    "diagcab": colour_archive,
    "djprojects": colour_archive,
    "dl_": colour_archive,
    "dlc": colour_archive,
    "dms": colour_archive,
    "drs": colour_archive,
    "drz": colour_archive,
    "dtsx": colour_archive,
    "dtz": colour_archive,
    "dub": colour_archive,
    "eappx": colour_archive,
    "ear": colour_archive,
    "edz": colour_archive,
    "egg": colour_archive,
    "emk": colour_archive,
    "enc4": colour_archive,
    "enlx": colour_archive,
    "enpack": colour_archive,
    "ex_": colour_archive,
    "fb": colour_archive,
    "fcxe": colour_archive,
    "flmod": colour_archive,
    "fmu": colour_archive,
    "fpk": colour_archive,
    "frp": colour_archive,
    "fwp": colour_archive,
    "gbx": colour_archive,
    "gca": colour_archive,
    "gip": colour_archive,
    "gpk": colour_archive,
    "gr_": colour_archive,
    "gro": colour_archive,
    "gta": colour_archive,
    "gtar": colour_archive,
    "gxx": colour_archive,
    "gz": colour_archive,
    "gzip": colour_archive,
    "ha": colour_archive,
    "hbc": colour_archive,
    "hpa": colour_archive,
    "hqx": colour_archive,
    "htmlz": colour_archive,
    "ice": colour_archive,
    "igz": colour_archive,
    "iha": colour_archive,
    "imoviemobile": colour_archive,
    "inv": colour_archive,
    "ipa": colour_archive,
    "isz": colour_archive,
    "iwa": colour_archive,
    "iwd": colour_archive,
    "ize": colour_archive,
    "ja": colour_archive,
    "jar": colour_archive,
    "jso": colour_archive,
    "kep": colour_archive,
    "kgb": colour_archive,
    "kge": colour_archive,
    "kz": colour_archive,
    "lg": colour_archive,
    "lha": colour_archive,
    "lime": colour_archive,
    "lrz": colour_archive,
    "lz": colour_archive,
    "lz4": colour_archive,
    "lzh": colour_archive,
    "lzo": colour_archive,
    "lzp": colour_archive,
    "lzs": colour_archive,
    "lzw": colour_archive,
    "lzx": colour_archive,
    "macbin": colour_archive,
    "maff": colour_archive,
    "mcp": colour_archive,
    "md5": colour_archive,
    "mdzip": colour_archive,
    "mou": colour_archive,
    "mpkg": colour_archive,
    "mpq": colour_archive,
    "ms_": colour_archive,
    "msa": colour_archive,
    "mshc": colour_archive,
    "msu": colour_archive,
    "mtf": colour_archive,
    "mva": colour_archive,
    "mvdx": colour_archive,
    "myo": colour_archive,
    "mzz": colour_archive,
    "nbh": colour_archive,
    "nfp": colour_archive,
    "nks": colour_archive,
    "nkx": colour_archive,
    "nmd": colour_archive,
    "nsarc": colour_archive,
    "nuget": colour_archive,
    "nupkg": colour_archive,
    "nw_": colour_archive,
    "nxm": colour_archive,
    "nz": colour_archive,
    "oap": colour_archive,
    "obr": colour_archive,
    "oiv": colour_archive,
    "opg": colour_archive,
    "oz": colour_archive,
    "pac": colour_archive,
    "pack": colour_archive,
    "pae": colour_archive,
    "paq": colour_archive,
    "pax": colour_archive,
    "pck": colour_archive,
    "pea": colour_archive,
    "phar": colour_archive,
    "piz": colour_archive,
    "pk1": colour_archive,
    "pka": colour_archive,
    "pkd": colour_archive,
    "pkg": colour_archive,
    "pkg_": colour_archive,
    "pma": colour_archive,
    "pn_": colour_archive,
    "ppk": colour_archive,
    "propdesc": colour_archive,
    "psa": colour_archive,
    "pug": colour_archive,
    "pup": colour_archive,
    "puz": colour_archive,
    "pwzip": colour_archive,
    "pzip": colour_archive,
    "qar": colour_archive,
    "qcf": colour_archive,
    "qif": colour_archive,
    "qze": colour_archive,
    "rar": colour_archive,
    "rar1": colour_archive,
    "rar5": colour_archive,
    "rarx": colour_archive,
    "rbz": colour_archive,
    "rev": colour_archive,
    "rez": colour_archive,
    "rfa": colour_archive,
    "rgss2a": colour_archive,
    "roo": colour_archive,
    "rpa": colour_archive,
    "rpm": colour_archive,
    "rwp": colour_archive,
    "rxx": colour_archive,
    "rz": colour_archive,
    "rzr": colour_archive,
    "s09": colour_archive,
    "sar": colour_archive,
    "saz": colour_archive,
    "sbc": colour_archive,
    "sea": colour_archive,
    "sfpack": colour_archive,
    "shar": colour_archive,
    "shr": colour_archive,
    "sip": colour_archive,
    "sisx": colour_archive,
    "sit": colour_archive,
    "sitx": colour_archive,
    "slf": colour_archive,
    "snappy": colour_archive,
    "snoop": colour_archive,
    "solitairetheme8": colour_archive,
    "soundpack": colour_archive,
    "spk": colour_archive,
    "spkg": colour_archive,
    "split": colour_archive,
    "srep": colour_archive,
    "srr": colour_archive,
    "sue": colour_archive,
    "swm": colour_archive,
    "tar": colour_archive,
    "tar.gz": colour_archive,
    "tar.xz": colour_archive,
    "tbz": colour_archive,
    "tg": colour_archive,
    "tgz": colour_archive,
    "tot": colour_archive,
    "tsk": colour_archive,
    "tx_": colour_archive,
    "txz": colour_archive,
    "tz": colour_archive,
    "u3p": colour_archive,
    "uax": colour_archive,
    "ufdr": colour_archive,
    "uha": colour_archive,
    "unitypackage": colour_archive,
    "uti": colour_archive,
    "utx": colour_archive,
    "uue": colour_archive,
    "uvz": colour_archive,
    "uzip": colour_archive,
    "vem": colour_archive,
    "vfs": colour_archive,
    "vl2": colour_archive,
    "vol1.egg": colour_archive,
    "vsix": colour_archive,
    "vty": colour_archive,
    "wad": colour_archive,
    "wapt": colour_archive,
    "war": colour_archive,
    "warc": colour_archive,
    "wbpz": colour_archive,
    "wdz": colour_archive,
    "webarchive": colour_archive,
    "wlpk": colour_archive,
    "wmz": colour_archive,
    "wz": colour_archive,
    "xap": colour_archive,
    "xdelta": colour_archive,
    "xfl": colour_archive,
    "xip": colour_archive,
    "xsn": colour_archive,
    "xx": colour_archive,
    "xxl": colour_archive,
    "xz": colour_archive,
    "xzm": colour_archive,
    "y": colour_archive,
    "yar": colour_archive,
    "ymp": colour_archive,
    "yz": colour_archive,
    "z": colour_archive,
    "z20": colour_archive,
    "zap": colour_archive,
    "zar": colour_archive,
    "zds": colour_archive,
    "zfc": colour_archive,
    "zfs": colour_archive,
    "zfsendtotarget": colour_archive,
    "zi": colour_archive,
    "zim": colour_archive,
    "zip2": colour_archive,
    "zipx": colour_archive,
    "zl": colour_archive,
    "zlib": colour_archive,
    "zoo": colour_archive,
    "zpaq": colour_archive,
    "zsplit": colour_archive,
    "zx01": colour_archive,
    "zxp": colour_archive,
    "appdata": colour_virt,
    "appicon": colour_virt,
    "appinfo": colour_virt,
    "avhd": colour_virt,
    "dsk": colour_virt,
    "efd": colour_virt,
    "fdd": colour_virt,
    "hds": colour_virt,
    "img": colour_virt,
    "kbd": colour_virt,
    "mem": colour_virt,
    "menudata": colour_virt,
    "ova": colour_virt,
    "pki": colour_virt,
    "psf": colour_virt,
    "pvc": colour_virt,
    "pvi": colour_virt,
    "pvm": colour_virt,
    "qcow": colour_virt,
    "qcow2": colour_virt,
    "qvm": colour_virt,
    "std": colour_virt,
    "syndarticle": colour_virt,
    "tvr": colour_virt,
    "vbox": colour_virt,
    "vbox-extpack": colour_virt,
    "vmac": colour_virt,
    "vmba": colour_virt,
    "vmcx": colour_virt,
    "vmdk-converttmp": colour_virt,
    "vmlog": colour_virt,
    "vmoapp": colour_virt,
    "vmpl": colour_virt,
    "vmt": colour_virt,
    "vmwarevm": colour_virt,
    "vpc6": colour_virt,
    "vpc7": colour_virt,
    "vswp": colour_virt,
    "xml-prev": colour_virt,
    "xva": colour_virt,
    "xvm": colour_virt,
    "zrp": colour_virt,
}

__shebang_colours = {
    "#!/usr/bin/env python": colour_py,
    "#!/usr/bin/python": colour_py,
    "#!python": colour_py,
    "#!/usr/bin/env python2": colour_py,
    "#!/usr/bin/python2": colour_py,
    "#!python2": colour_py,
    "#!/usr/bin/env python3": colour_py,
    "#!/usr/bin/python3": colour_py,
    "#!python3": colour_py,
    "#!/usr/bin/env bash": colour_bash,
    "#!/bin/bash": colour_bash,
    "#!/bin/sh": colour_bash,
    "#/usr/local/bin/bash": colour_bash,
}

__shebang_max_length = len(max(__shebang_colours))
