.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "BASH\-DEBUG\-SUBSHELL" "1" "January 2023" ""
.SH "NAME"
\fBbash\-debug\-subshell\fR \- debug bash script in a subshell
.SH "SYNOPSIS"
Debug bash script in a subshell, with \fBset \-euxo pipefail;\fR enabled\.
.SH "RETURN VALUES"
\fBexit 0\fR on success\. Anything if the script ends abruptly\.
.SH "SYNTAX"
\fBbash\-debug\-subshell <script\.sh> [<\'command1; \|\.\|\.\|\.; commandN;\'>]\fR
.SH "AUTHOR"
github \fIgithub\.com/gerelef/\fR
.SH "SECURITY CONSIDERATIONS"
I try to keep up to the latest security practices, however I do not hold these practices religiously, nor should you\. Some configuration files take security more seriously than others, and some do not take it into consideration at all\.
