.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "TIMEIT" "1" "January 2023" ""
.SH "NAME"
\fBtimeit\fR \- time process real time N times
.SH "SYNOPSIS"
Run & time process N times, display average real time\.
.SH "RETURN VALUES"
\fB2\fR on not enough arguments\.
.SH "SYNTAX"
\fBtimeit <num> <command> [<arg1 \|\.\|\.\|\. argN>]\fR
.SH "AUTHOR"
StackOverflow @marian0 && @Kyle \fIhttps://stackoverflow\.com/a/57313672/10007109\fR
