#!/usr/bin/env bash

# HELP one-liner to check if dependencies exist

depends-on () (
    hasErrors=""
    for arg in "$@"; do
        if test -z "$(command -v $arg)"; then
            _is-tty && >&2 echo "$(tput setaf 3)WARN: dependency $(tput bold)$arg$(tput sgr0)$(tput setaf 3) not found!$(tput sgr0)"
            hasErrors="yes"
        fi
    done
    exit $(test -z $hasErrors)
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && depends-on $@
