#!/usr/bin/env bash

echo-status () (
    # echo for status updates
    tput setaf 6 # cyan
    echo "[STATUS] [$(date +"%H:%M:%S")] $@"
    tput sgr0

    echo "[STATUS] $@" | systemd-cat --identifier="setup.sh" --priority="notice"
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && echo-status "$@"
