#!/usr/bin/env bash

echo-success () (
    tput setaf 2 # green
    tput bold
    echo "[SUCCESS] [$(date +"%H:%M:%S")] $@"
    tput sgr0

    echo "[SUCCESS] $@" | systemd-cat --identifier="setup.sh" --priority="notice"
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && echo-success "$@"
