#!/usr/bin/env bash

# HELP echo important txt

echo-important () (
    tput setaf 3 # yellow
    tput bold
    echo "[IMPORTANT] [$(date +"%H:%M:%S")] $@"
    tput sgr0

    echo "[IMPORTANT] $@" | systemd-cat --identifier="setup.sh" --priority="notice"
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && echo-important "$@"
