#!/usr/bin/env bash

readonly HYPRLAND_PACKAGES="hyprland \
hyprlock \
hyprcursor \
waybar \
hyprnome \
hyprshot \
waypaper \
hyprpaper \
swww \
wofi \
"

sudo dnf copr enable -y "solopasha/hyprland"
sudo dnf install -y --refresh --best --allowerasing $HYPRLAND_PACKAGES

sudo tee "/usr/local/bin/hyprland-minimize" <<END
#!/usr/bin/env bash

if [ "\$(hyprctl activewindow -j | jq -r ".class")" = "Steam" ]; then
    xdotool getactivewindow windowunmap
else
    hyprctl dispatch killactive ""
fi
END

sudo chmod 755 "/usr/local/bin/hyprland-minimize"
sudo chown root:root "/usr/local/bin/hyprland-minimize"

# TODO configure waybar
# TODO find an app launcher or some shit? lmao
# TODO set monitor config
