#!/usr/bin/env bash

# HELP check if currently running as root

is-root () (
    _echo-debug "is-root $(id -u) $? (0 is root)"
    [[ $(id -u) = 0 ]] && return 0
    return 1
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-root "$@"
