#!/usr/bin env bash

# HELP check if running under uefi

is-uefi () (
    echo-debug "is-uefi $([ -d /sys/firmware/efi ] && echo UEFI || echo BIOS)"
    [[ "$([ -d /sys/firmware/efi ] && echo UEFI || echo BIOS)" == "UEFI" ]] && return 0
    return 1
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-uefi "$@"
