#!/usr/bin/env bash

# HELP check if rootfs is btrfs

_depends-on stat || exit

is-btrfs-rootfs () (
    root_fs="$(stat -f --format=%T /)"
    _echo-debug "is-btrfs-rootfs $root_fs"
    [[ "btrfs" == $root_fs ]] && return 0
    return 1
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-btrfs-rootfs "$@"
