#!/usr/bin/env bash

# HELP one-liner to check if output is going to a tty (terminal)

is-tty () (
    test -t 1
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-tty $@
