#!/usr/bin/env bash

# HELP check if running under gnome

is-gnome-session () (
    _echo-debug "is-gnome-session $XDG_CURRENT_DESKTOP"
    [[ $XDG_CURRENT_DESKTOP == "GNOME" ]] && return 0
    return 1
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-gnome-session "$@"
