#!/usr/bin/env bash

# HELP check if nvidia gpu is available

is-nvidia-gpu () (
    (lspci | grep -i vga | grep NVIDIA) && return 0
    return 1
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-nvidia-gpu "$@"
