#!/usr/bin env bash

# HELP get the nvidia gpu model

get-nvidia-gpu-model () (
    readonly mdl="$(lspci | grep -i vga | grep NVIDIA | grep -E --only-matching "(\[.+\])" | tr -d '[]')"
    echo "$mdl"
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && get-nvidia-gpu-model "$@"
