#!/usr/bin/env bash

if [[ -z "$(command -v adb)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

adb-list-all-devices () (
    if [[ $# != 1 ]]; then echo "State argument must be given!"; exit 1; fi
    # "device" state is the correct state here for authorized devices
    adb devices | grep $1 | awk '{ if (NR > 1) { printf $1 " " } }' | xargs
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-list-all-devices $@