#!/usr/bin/env bash

if [[ -z "$(command -v adb)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

adb-toggle-screen () (
    adb shell input keyevent KEYCODE_POWER
)

adb-toggle-screen
