#!/usr/bin/env bash

# HELP adb-uninstall-package "id" "package.name"; uninstall package for phone id

_depends-on adb || exit

adb-uninstall-package () (
    if [[ $# != 2 ]]; then echo "id, package arguments must be given!"; exit 1; fi
    adb -s $1 uninstall --user 0 $2
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-uninstall-package $@
