#!/usr/bin/env bash

# HELP adb-list-all-devices "state"; get all devices with "state"

_depends-on adb || exit

adb-list-all-devices () (
    if [[ $# != 1 ]]; then echo "State argument must be given!"; exit 1; fi
    # "device" state is the correct state here for authorized devices
    adb devices | grep $1 | awk '{ if (NR > 1) { printf $1 " " } }' | xargs
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-list-all-devices $@
