#!/usr/bin/env bash

if [[ -z "$(command -v adb)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

adb-clear-caches () (
    if [[ $# != 2 ]]; then echo "id, package arguments must be given!"; exit 1; fi
    adb -s $1 shell pm clear $2
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-clear-caches $@