#!/usr/bin/env bash

# HELP 'uninstall' known bloatware/spyware applications w/o root via adb

_depends-on adb || exit

adb-remove-bloat () (
    # remove AppCloud, malware piece of backdoor shit
    adb uninstall --user 0 com.aura.oobe.samsung.gl
    adb uninstall --user 0 com.aura.oobe.samsung
    adb uninstall --user 0 com.ironsource.appcloud.oobe.hutchison
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-remove-bloat "$@"
