#!/usr/bin/env bash

# HELP setup adb to work with usb debugging (over hotspot)

if [[ -z "$(command -v adb)" ]]; then
    echo "Cannot run $(basename $0) without adb! Exiting..."
    exit 1
fi

adb-setup-hotspot-wireless-debug () (
    if [[ $# != 1 ]]; then echo "device ip must be given!"; exit 1; fi
    adb tcpip 5555 | exit
    adb connect "$1" | exit
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-setup-hotspot-wireless-debug $@
