#!/usr/bin/env bash

# HELP ask-user <question>; ask the user a yes or no question; returns 0 on 'yes'

# do NOT use this for anything else other than echoing from a call whose stdout is meant to be caught!
# use _echo-debug for debug information, and _echo-important and friends for everything else
# https://stackoverflow.com/questions/2990414/echo-that-outputs-to-stderr
_echo-stderr () (
    echo "$@" 1>&2
)

ask-user-input () (
    while : ; do
        read -p "$*: " -r
        if [[ $REPLY =~ ^[A-Za-z\ ]$ ]];
            echo "$REPLY"
            return 0
        fi
        _echo-stderr ""
        _echo-stderr "Invalid reply \"$REPLY\", please answer in the following range: ^[A-Za-z\ ]"
    done
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ask-user-input "$@"
