#!/usr/bin/env bash

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# ffmpeg compress mp3 audio
ffcompress-mp3 () (
    [[ -z "$*" ]] && return 2 
    [[ "$#" -ne 2 ]] && return 2
    # $1 input
    # $2 bitrate (e.g. 96k)
    local output=$(basename -- "${1%.*}")
    ffmpeg -i "$1" -map 0:a:0 -b:a "$2" "$PWD/output-compressed.mp3"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffcompress-mp3 "$@"
