#!/usr/bin/env bash

# ffmpeg compress mp3 audio
ffcompress-mp3 () (
    [[ -z "$*" ]] && return 2 
    [[ "$#" -ne 2 ]] && return 2
    # $1 input
    # $2 bitrate (e.g. 96k)
    local output=$(basename -- "${1%.*}")
    ffmpeg -i "$1" -map 0:a:0 -b:a "$2" "$PWD/output-compressed.mp3"
)

ffcompress-mp3 "$@"