#!/usr/bin/env bash

# HELP ffcompress-mp4 <file> <crf x265 log value>; compress an mp4 using x265; good crf values are 27 to 30

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# ffmpeg compress mp4 video
ffcompress-mp4 () (
    [[ -z "$*" ]] && return 2 
    [[ "$#" -ne 2 ]] && return 2
    # $1 input
    # $2 crf logarithmic value for x265
    #  good values are from 27 to 30
    local output=$(basename -- "${1%.*}")
    ffmpeg -i "$1" -vcodec libx265 -crf "$2" -vsync cfr -r 60 "$PWD/$output-compressed.mp4"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffcompress-mp4 "$@"
