#!/usr/bin/env bash

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# ffmpeg convert audio file to mp3
ffconvert-mp3 () (
    [[ -z "$*" ]] && return 2 
    for arg in "$@"; do
        local output=$(basename -- "${arg%.*}")
        ffmpeg -i "$arg" -acodec libmp3lame "$PWD/$output-converted.mp3"  1> /dev/null
        echo "Done $output-converted"
    done
)

ffconvert-mp3 "$@"