#!/usr/bin/env bash

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# ffmpeg extract video from video with audio to mp3
ffextract-video-mp4 () (
    [[ -z "$*" ]] && return 2
    for arg in "$@"; do
        local output=$(basename -- "${arg%.*}")
        ffmpeg -i "$arg" -c copy -an "$PWD/$output-video.mp4" 1> /dev/null
        echo "Done $output-video"
    done
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffextract-video-mp4 "$@"
