#!/usr/bin/env bash

# HELP ffextract-audio-mp3 <file1> <file2> <...>; extract audio from video with audio to mp3

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

ffextract-audio-mp3 () (
    [[ -z "$*" ]] && return 2
    for arg in "$@"; do
        local output=$(basename -- "${arg%.*}")
        ffmpeg -i "$arg" -vn "$PWD/$output-audio.mp3" 1> /dev/null
        echo "Done $output-audio"
    done
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffextract-audio-mp3 "$@"
