#!/usr/bin/env bash

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# convert Minutes:Seconds (colon seperated) to seconds
__hms () (
    echo "$1" | awk -F: '{ print ($1 * 60) + $2 }';
)

# ffmpeg trim mp4 from start to end and convert to gif
ffgiphify () (
    [[ -z "$*" ]] && return 2 
    [[ "$#" -ne 3 ]] && return 2
    # $1 input
    # $2 start m:s 
    # $3 end   m:s
    local output=$(basename -- "${1%.*}")
    local palette="/tmp/$output-palette.png"
    ffmpeg -i "$1" -filter_complex "[0:v] palettegen" "$palette" 1> /dev/null
    ffmpeg -ss "$(__hms "$2")" -to "$(__hms "$3")" -i "$1" -i "$palette" -filter_complex "[0:v] paletteuse" "$PWD/$output-giphified.gif" 1> /dev/null
    rm -v "$palette"
    echo "Done $output-giphified"
)

ffgiphify "$@"