#!/usr/bin/env bash

# HELP ffscale-mp4 <file> <width:height>; scale video file to selected resolution

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# convert (X,Y) coords with X delimiter instead of comma to ffmpeg format
__xy_to_ffilter_coords () (
    echo "$1" | awk -Fx '{ print $1":"$2 }';
)

ffscale-mp4 () (
    [[ -z "$*" ]] && return 2
    [[ "$#" -ne 2 ]] && return 2
    # $1 input
    # $2 width:height
    local output=$(basename -- "${1%.*}")
    ffmpeg -i "$1" -vf scale="$(__xy_to_ffilter_coords "$2")" -vcodec libx265 -crf 22 -vsync cfr -r 60 "$PWD/$output-scaled.mp4"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffscale-mp4 "$@"