#!/usr/bin/env bash

# HELP ffset-fps <file> <fps>; convert a video from whatever framerate to <fps>

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# ffmpeg set fps video
ffset-fps () (
    [[ -z "$*" ]] && return 2
    [[ "$#" -ne 2 ]] && return 2
    # $1 input
    # $2 crf logarithmic value for x265
    #  good values are from 27 to 30
    local output=$(basename -- "${1%.*}")
    ffmpeg -i "$1" -filter:v "fps=$2" "$PWD/$output-fps-$2.mp4"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffset-fps "$@"
