#!/usr/bin/env bash

# HELP ffset-fps <file> <fps>; convert a video from whatever framerate to <fps>

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# ffmpeg set fps video
ffset-fps () (
    [[ -z "$*" ]] && return 2
    [[ "$#" -ne 2 ]] && return 2
    readonly input_fps_division=$(ffprobe -v error -select_streams v:0 -show_entries stream=avg_frame_rate -of default=nw=1:nk=1 "$1")
    readonly input_fps=$(python3 -c "print('{:.2f}'.format($input_fps_division))")  # convert to xx.xx format
    readonly scalar=$(python3 -c "print('{:.2f}'.format($output_fps / $input_fps))")
    # $1 input mp4
    # $2 output fps
    local output=$(basename -- "${1%.*}")
    ffmpeg -itsscale "$scalar" -i "$1" -r "$2" -c copy "$PWD/$output-fps-$2.mp4"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffset-fps "$@"
