#!/usr/bin/env bash

# HELP fftrim-mp4 <file> <sta:rt> <end:ing>; trim mp4 from start to end

if [[ -z "$(command -v ffmpeg)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

# convert Minutes:Seconds (colon seperated) to seconds
__hms () (
    echo "$1" | awk -F: '{ print ($1 * 60) + $2 }';
)

fftrim-mp4 () (
    [[ -z "$*" ]] && return 2 
    [[ "$#" -ne 3 ]] && return 2
    # $1 input
    # $2 start (seconds)
    # $3 end   (seconds)
    local output=$(basename -- "${1%.*}")
    ffmpeg -ss "$(__hms "$2")" -to "$(__hms "$3")" -i "$1" -codec copy "$PWD/$output-trimmed.mp4"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && fftrim-mp4 "$@"