#!/usr/bin/env bash

ffvideofy () (
    [[ -z "$*" ]] && return 2 
    [[ "$#" -ne 2 ]] && return 2
    # $1 image
    # $2 audio
    local output=$(basename -- "${1%.*}")
    local output+=$(basename -- "${2%.*}")
    
    ffmpeg -loop 1 -y -i "$1" -i "$2" -vcodec libx265 -shortest "$PWD/$output.mp4"
)

ffvideofy "$@"