#!/usr/bin/env bash

# HELP list all connected devices (except self) ipv4

ip-all-devices-ipv4 () (
    if [[ $# != 1 ]]; then echo "interface ip argument must be given!"; exit 1; fi
    nmap -n -sn "$1/24" -oG - | awk '/Up$/{print $2}' | grep --invert-match "$1"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ip-all-devices-ipv4 $@
