#!/usr/bin/env bash

json-roulette () {
    curl --tlsv1.2 -fsSL "https://raw.githubusercontent.com/gerelef/json-roulette/master/json-roulette.py" | python3 - "$@"
}

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && json-roulette "$@"
