#!/usr/bin/env bash

# HELP usage: json-roulette --pretty --size 5 --word-sample-size 15 --composites-size-low 3 --composites-size-high 7; a barebones json generator, for testing

_depends-on curl python3 || exit

json-roulette () {
    curl --tlsv1.2 -fsSL "https://raw.githubusercontent.com/gerelef/json-roulette/master/json-roulette.py" | python3 - "$@"
}

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && json-roulette "$@"
