#!/usr/bin/env bash

# HELP a spiritual reimplementation of GNU Stow, but simpler, for tinkerers.

_depends-on curl python3 || exit

pstow () {
    curl --tlsv1.2 -fsSL "https://raw.githubusercontent.com/gerelef/pstow/master/pstow.py" | python3 - "$@"
}

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && pstow "$@"
