#!/usr/bin/env bash

readonly SHELL_REQUIREMENTS="$HOME/dotfiles/.shell-requirements"
readonly HAS_RUN_DIR="/opt"
readonly HAS_RUN_FILE="$HAS_RUN_DIR/.has-run"
readonly HAS_RUN_OPTS_FILE="$HAS_RUN_DIR/.has-run-opts"

has-run () (
    [[ -f "$HAS_RUN_FILE" ]] && [[ -f "$HAS_RUN_OPTS_FILE" ]] && return 0
    return 1
)

mk-run-file () (
    [[ ! -d "$HAS_RUN_DIR" ]] && sudo mkdir -p "$HAS_RUN_DIR"
    sudo touch $HAS_RUN_FILE
)

mk-run-opts-file () (
    [[ ! -d "$HAS_RUN_DIR" ]] && sudo mkdir -p "$HAS_RUN_DIR"
    sudo touch $HAS_RUN_OPTS_FILE
)

install-system-pkg () (
    while :; do
        if [[ -n "$(command -v dnf)" ]]; then
            sudo dnf install -y "$@" || exit
            break
        fi
        if [[ -n "$(command -v yum)" ]]; then
            sudo yum install -y "$@" || exit
            break
        fi
        if [[ -n "$(command -v apt)" ]]; then
            sudo apt install -y "$@" || exit
        fi
        break
    done
)

require-login-shell-packages () (
    has-run && return 0

    mapfile -t required_dependencies < $SHELL_REQUIREMENTS
    if [[ -n "$required_dependencies" ]]; then
        echo -e "Installing essential shell packages: \033[38;5;39m"
        echo -n "${required_dependencies[*]}"
        echo -e "\033[0m"

        install-system-pkg "${required_dependencies[@]}" || return
        mk-run-file
    fi

    if ask-user 'Do you want to install optional packages?'; then
        echo -e "Installing optional shell packages: \033[38;5;39m"
        echo -n "micro lsd zoxide --exclude=fzf"
        echo -e "\033[0m"
        install-system-pkg "fish" "micro" "lsd" "zoxide" "--exclude=fzf"
        mk-run-opts-file
    fi

    clear
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && require-login-shell-packages "$@"
