#!/usr/bin/env bash

readonly SHELL_REQUIREMENTS="$HOME/dotfiles/.shell-requirements"
readonly HAS_RUN_DIR="$HOME/.config"
readonly HAS_RUN_FILE="$HAS_RUN_DIR/.has-run"

has-run () (
    [[ -f "$HAS_RUN_FILE" ]] && exit 0
    exit 1
)

mk-run-file () (
    [[ ! -d "$HAS_RUN_DIR" ]] && mkdir "$HAS_RUN_DIR"
    touch $HAS_RUN_FILE
)

install-system-pkg () (
    while :; do
        if [[ -n "$(command -v dnf)" ]]; then
            sudo dnf install -y "$@" || exit 
            break
        fi
        if [[ -n "$(command -v yum)" ]]; then
            sudo yum install -y "$@" || exit 
            break
        fi
        if [[ -n "$(command -v apt)" ]]; then
            sudo apt install -y "$@" || exit
        fi 
        break
    done
)

require-login-shell-packages () (
    has-run && return 0

    mapfile -t required_dependencies < $SHELL_REQUIREMENTS
    
    if [[ -n "$required_dependencies" ]]; then 
        echo -e "Installing essential shell packages: \033[38;5;39m"
        echo -n "${required_dependencies[*]}"
        echo -e "\033[0m"

        install-system-pkg "${required_dependencies[@]}" || return
        mk-run-file
        clear
    fi
)

require-login-shell-packages "$@"