#!/usr/bin/env bash

if [[ -z "$(command -v curl)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

curl-bearer-token () (
    echo $(curl -sS --dump-header - --cookie-jar -L -b "" -X GET "https://open.spotify.com/" | grep --only-matching --extended-regexp '"accessToken":".+","accessTokenExpirationTimestampMs' | sed -nr 's/"accessToken":"(.+)","accessTokenExpirationTimestampMs/\1/p' -)
)

spotify-dump-playlist () (
    if [[ $# != 1 ]]; then
        echo "playlist url must be given!"
        exit 1
    fi
    filename_and_queries="$(basename $1))"
    readonly playlist_id="${filename_and_queries%?*}"
    readonly bearer_header="Authorization: Bearer $(curl-bearer-token)"
    # getting the name of playlist: jq '.name'
    # getting the name of all tracks: jq '.tracks.items.[].track.name'
    # getting the name of first artist: jq '.tracks.items.[].track.artists.[0].name'
    # getting the next page: jq '.tracks.next'
    # if .tracks.next -ne null, get the next batch
    body="$(curl -sS --cookie-jar -L -b "" -H "$bearer_header" -X GET "https://api.spotify.com/v1/playlists/$playlist_id")"
    next_page="$(echo "$body" | jq '.tracks.next' | tr -d "\"")"
    readonly fname="$(echo "$body" | jq '.name' | tr -d "\"" | tr -d "'")"
    readarray -t track_names < <(echo "$body" | jq '.tracks.items.[].track.name')
    readarray -t artist_names < <(echo "$body" | jq '.tracks.items.[].track.artists.[0].name')
    for i in "${!track_names[@]}"; do
        echo "$(echo ${artist_names[i]} | tr -d "\"") - $(echo ${track_names[i]} | tr -d "\"")" >> "$fname"
    done
    while [[ "$next_page" != "null" && -n "$next_page" ]]; do
        body="$(curl -sS --cookie-jar -L -b "" -H "$bearer_header" -X GET "$next_page")"
        next_page="$(echo "$body" | jq '.tracks.next' | tr -d "\"")"
        readarray -t track_names < <(echo "$body" | jq '.items.[].track.name')
        readarray -t artist_names < <(echo "$body" | jq '.items.[].track.artists.[0].name')
        for i in "${!track_names[@]}"; do
            echo "$(echo ${artist_names[i]} | tr -d "\"") - $(echo ${track_names[i]} | tr -d "\"")" >> "$fname"
        done
    done
    echo "$fname"
)

spotify-dump-playlist $@