#!/usr/bin/env python3

import sys
from datetime import date, datetime
from dateutil.relativedelta import relativedelta

# HELP until <<year> [<month>] [<day>] | <next> <year | month>>; calculate how many years, months, days till args

def until(year: str) -> str:
    diff = relativedelta(year, date.today())
    return f"{diff.years} years, {diff.months} months, {diff.days} days"

if __name__ == "__main__":
    if len(sys.argv) < 2:
        exit(2)

    if sys.argv[1] == "next":
        if len(sys.argv) != 3:
            exit(2)

        today = datetime.now().date()
        if "year" == sys.argv[2]:
            print(until(datetime(today.year + 1, 1, 1).date()))
            exit(0)
        if "month" == sys.argv[2]:
            if today.month == 12:
                print(until(datetime(today.year + 1, 1, 1).date()))
                exit(0)
            print(until(datetime(today.year, today.month + 1, 1).date()))
            exit(0)
        exit(2)
    year = sys.argv[1]
    month = sys.argv[2] if len(sys.argv) >= 3 else 1
    day = sys.argv[3] if len(sys.argv) >= 4 else 1
    try:
        print(until(date(year=int(year), month=int(month), day=int(day))))
    except ValueError:
        print("Arguments must be integers!", file=sys.stderr)
        exit(2)
