#!/usr/bin/env bash

update-everything () (
    echo "$(tput bold)$(tput setaf 6)────>Updating w/ package manager...$(tput sgr0)"
    # the reason this for loop exists is to act as a "block", so we can break control flow
    #  when we're done updating platform packages (since there will be only 1 package manager per sys)
    while :; do
        if [[ -n "$(command -v dnf)" ]]; then
            sudo dnf upgrade -y --refresh || exit
            sudo dnf autoremove -y || exit
            break
        fi
        if [[ -n "$(command -v pacman)" ]]; then
            sudo pacman -Syu || exit
            # recursively remove orphans and their configuration files
            sudo pacman -Qdtq | sudo pacman -Rns - 2> /dev/null
            break
        fi
        if [[ -n "$(command -v apt)" ]]; then
            # no exit here; we might error, since http or ftp mirrors are apt source_list by default 
            sudo apt update -y || break
            sudo apt upgrade -y || break
            sudo apt autoremove -y || break
            break
        fi

        echo "No package manager found! Omitting system updates..."
        break
    done

    if [[ -n "$(command -v flatpak)" ]]; then
        echo "$(tput bold)$(tput setaf 6)────>Updating flatpak...$(tput sgr0)"        
        flatpak update -y || exit 
        flatpak uninstall --unused -y || exit
        sudo flatpak repair || exit
    fi 
    
    if [[ -n "$(command -v snap)" ]]; then
        echo "$(tput bold)$(tput setaf 6)────>Updating snap...$(tput sgr0)"
        snap refresh -y || exit
    fi 

    if [[ -n "$(command -v selenium-manager)" ]]; then
        echo "$(tput bold)$(tput setaf 6)────>Updating chromedriver...$(tput sgr0)"
        # no exit here; we might error since this often gets drivers from file-sharing hosts (e.g. google-drive)
        selenium-manager --debug --browser chrome 
    fi

    if [[ -n "$(command -v npm)" ]]; then
        echo "$(tput bold)$(tput setaf 6)────>Updating npm...$(tput sgr0)"
        sudo npm install -g npm@latest || exit
    fi

    echo "$(tput bold)$(tput setaf 6)────>Updating indexes...$(tput sgr0)"
    [[ -n "$(command -v updatedb)" ]] && sudo updatedb
    [[ -n "$(command -v update-grub)" ]] && sudo update-grub
    return 0
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && update-everything "$@"