#!/usr/bin/env bash

# HELP update zed, the snappy text editor

_depends-on curl tar || exit

install-zed-text-editor () (
    echo "Installing zed..."
    echo "downloading zed to /tmp/zed-install/zed-linux-x86_64.tar.gz"

    # step 1 extract & move to /opt/zed.app
    mkdir "/tmp/zed-install"
    curl -L "https://zed.dev/api/releases/stable/latest/zed-linux-x86_64.tar.gz" --output "/tmp/zed-install/zed-linux-x86_64.tar.gz"
    sudo tar xf "/tmp/zed-install/zed-linux-x86_64.tar.gz" --directory=/opt
    rm -rf "/tmp/zed-install"  # remove tmp dir, unneeded
    echo "extracted zed to /opt/zed.app"

    sudo chmod -R 755 "/opt/zed.app"
    sudo chown -R root:root "/opt/zed.app"
    # step 2. link binary to /usr/local/bin
    sudo ln -sf "/opt/zed.app/bin/zed" "/usr/local/bin/zed"
    # step 3. place & replace zed.app/share in /usr/
    sudo chmod -R 644 "/opt/zed.app/share"
    sudo chown -R root:root "/opt/zed.app/share"
    sudo cp -f "/opt/zed.app/share/applications/zed.desktop" "/usr/share/applications/zed.desktop"
    sudo cp -f "/opt/zed.app/share/icons/hicolor/512x512/apps/zed.png" "/usr/share/icons/zed.png"

    # bash language support
    sudo dnf install -y --best --allowerasing --skip-unavailable \
    nodejs-bash-language-server \
    shellcheck

    echo "Done."
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && install-zed-text-editor "$@"
