#!/usr/bin/env bash

# HELP install ollama, the LLM CLI

create-ollama-systemd-unit () (
    mkdir -p ~/.config/systemd/user/

    cwd="$( cd -- "$( dirname -- ${BASH_SOURCE[0]} )" &> /dev/null && pwd )"
    cwd="${cwd:-$(pwd)}"
    systemctl --user enable "$cwd/units/ollama.service"
    systemctl --user daemon-reload
    systemctl --user start ollama
)

install-ollama () (
    echo "Installing ollama..."
    sudo curl -L "https://ollama.com/download/ollama-linux-amd64" -o "/usr/local/bin/ollama"
    sudo chmod 755 "/usr/local/bin/ollama"
    sudo chown root:root "/usr/local/bin/ollama"

    create-ollama-systemd-unit

    echo "Done."
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && install-ollama "$@"
