#!/usr/bin/env bash

# HELP update firefox-nightly

if [[ -z "$(command -v wget)" ]]; then
    echo "Cannot run $(basename $0) without wget! Exiting..."
    exit 1
fi

if [[ -z "$(command -v tar)" ]]; then
    echo "Cannot run $(basename $0) without tar! Exiting..."
    exit 1
fi

if [[ -z "$(command -v tee)" ]]; then
    echo "Cannot run $(basename $0) without tee! Exiting..."
    exit 1
fi

install-ff-nightly () (
    echo "Installing firefox-nightly..."
    echo "downloading firefox-nightly to /tmp/ff-install/firefox-nightly-latest"

    mkdir "/tmp/ff-install"
    wget -c --read-timeout=5 --tries=0 --content-disposition \
        'https://download.mozilla.org/?product=firefox-nightly-latest-ssl&os=linux64&lang=en-US' \
        -O '/tmp/ff-install/firefox-nightly-latest' || exit
    cd "/tmp/ff-install" && bunzip2 "/tmp/ff-install/firefox-nightly-latest"
    sudo tar -xf "/tmp/ff-install/firefox-nightly-latest.out" --directory=/opt || exit
    sudo chown -R "root:root" "/opt/firefox" || exit
    sudo chmod -R 755 "/opt/firefox" || exit
    sudo ln -sf "/opt/firefox/firefox-bin" "/usr/local/bin/firefox-nightly" || exit
    rm -rf "/tmp/ff-install"

    sudo tee "/usr/share/applications/firefox-nightly.desktop" <<TEE_END
[Desktop Entry]
Version=1.0
Name=Firefox Nightly
GenericName=Web Browser
Comment=Browse the Web
Exec=firefox-nightly %U
TryExec=firefox-nightly
Icon=/opt/firefox/browser/chrome/icons/default/default128.png
Terminal=false
Type=Application
StartupNotify=true
Categories=Network;WebBrowser;
Keywords=web;browser;internet;
Actions=new-window;new-private-window;profile-manager;

[Desktop Action new-window]
Name=New Window
Exec=firefox-nightly --new-window %U

[Desktop Action new-private-window]
Name=New Private Window
Exec=firefox-nightly --private-window %U

[Desktop Action profile-manager]
Name=Profile Manager
Exec=firefox-nightly -P %U
TEE_END

    echo "Done."
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && install-ff-nightly "$@"
