#!/usr/bin/env bash

update-ff-theme () (
    # for future reference: curl -fsSL https:// | bash -s -- - "~/dotfiles/.config/mozilla/userChrome.css" "$@"
    ~/dotfiles/scripts/utils/update-ff-theme.py --resource ~/dotfiles/.config/mozilla/userChrome.css "$@"
)

update-ff-theme "$@"