#!/usr/bin/env bash

# HELP install sublime-txt, via external repo

install-sublime-text-editor () (
    if [[ -z "$(command -v sublime-text)" ]]; then
        echo "Installing sublime-text ..."

        sudo rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg
        sudo dnf config-manager addrepo --from-repofile="https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo"
        sudo dnf install -y --best --allowerasing "sublime-text"

        echo "Done."
    fi

    sudo dnf upgrade -y sublime-text
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && install-sublime-text-editor "$@"
