#!/usr/bin/env bash

install-sublime-text-editor () (
    if [[ -z "$(command -v sublime-text)" ]]; then
        echo "Installing sublime-text ..."

        rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg
        dnf config-manager addrepo --from-repofile="https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo"
        dnf-install sublime-text

        echo "Done."
        return
    fi

    dnf upgrade -y sublime-text
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && install-sublime-text-editor "$@"
