#!/usr/bin/env bash

# HELP download & extract latest version of numerous game compatibility layers.

update-compat-layers () (
    "$HOME/dotfiles/scripts/utils/update-compat-layers.py" "$@"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && update-compat-layers "$@"
