#!/usr/bin/env bash

update-everything () (
    # the reason this for loop exists is to act as a "block", so we can break control flow
    #  when we're done updating platform packages (since there will be only 1 package manager per sys)
    while :; do
        if [[ -n "$(command -v dnf)" ]]; then
            sudo dnf upgrade -y --refresh || exit
            sudo dnf autoremove -y || exit
            break
        fi
        if [[ -n "$(command -v pacman)" ]]; then
            sudo pacman -Syu || exit
            break
        fi
        if [[ -n "$(command -v apt)" ]]; then
            sudo apt update -y || exit
            sudo apt upgrade -y || exit
            sudo apt autoremove -y || exit
            break
        fi
        break
    done
    
    if [[ -n "$(command -v flatpak)" ]]; then
        flatpak update -y || exit 
        flatpak uninstall --unused -y || exit
        sudo flatpak repair || exit
        break
    fi 
    
    if [[ -n "$(command -v snap)" ]]; then
        snap refresh -y || exit
        break
    fi 

    [[ -n "$(command -v updatedb)" ]] && sudo updatedb
    [[ -n "$(command -v update-grub)" ]] && sudo update-grub
    return 0
)

update-everything "$@"