#!/usr/bin/env bash

# HELP download an .mp3 file

_depends-on yt-dlp || exit

# yt-dlp download to mp3
ytdl-mp3 () (
    [[ -z "$*" ]] && return 2

    yt-dlp --extract-audio --audio-format mp3 --audio-quality 0 "$@"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ytdl-mp3 "$@"
