#!/usr/bin/env bash

# HELP download an .mp4 file

_depends-on yt-dlp || exit

# yt-dlp download to mp4
ytdl-mp4 () (
    [[ -z "$*" ]] && return 2

    yt-dlp --format "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]" "$@"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ytdl-mp4 "$@"
