#!/usr/bin/env bash

if [[ -z "$(command -v yt-dlp)" ]]; then
    echo "Cannot run $(basename $0) without dependency! Exiting..."
    exit 1
fi

ytdl-thumbnail () (
    [[ -z "$*" ]] && return 2
    
    yt-dlp --write-thumbnail --skip-download "$@"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ytdl-thumbnail "$@"