.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DOTFILES" "7" "December 2022" ""
.SH "NAME"
\fBdotfiles\fR \- configuration files for various applications
.SH "SYNOPSIS"
My personal dotfiles\. I do not recommend to anyone seeking inspiration to blindly copy\-paste my configs; they WILL introduce problems for you\. The contents of each rc file, especially the \.bashrc file, have been sourced by a variety of sources, including my personal experience & particularly my preferences\.
.P
There is no particular philosophy to these configuration files, it\'s all personal taste, and adhere to the latest versions of applications I use between my different personal computing platforms, which are, for the most part, running the same version\.
.SH "AUTHOR"
github \fIgithub\.com/gerelef/\fR
.SH "SECURITY CONSIDERATIONS"
I try to keep up to the latest security practices, however I do not hold these practices religiously, nor should you\. Some configuration files take security more seriously than others, and some do not take it into consideration at all\.
.SH "SEE ALSO"
dotfiles\-csgorc(7), dotfiles\-firefox(7), dotfiles\-man(7), dotfiles\-rc(7)
