#!/usr/bin/env bash

# HELP install required login shell packages

readonly SHELL_REQUIREMENTS="$HOME/dotfiles/.shell-requirements"

require-login-shell-packages () (
    MINIMUM_BASH_MAJOR_VERSION='5'
    if [[ "${BASH_VERSINFO[0]}" -lt $MINIMUM_BASH_MAJOR_VERSION ]]; then
        echo "Couldn't read file due to current BASH version being under $MINIMUM_BASH_MAJOR_VERSION"
        echo "Please prepend a bash shell that's over > $MINIMUM_BASH_MAJOR_VERSION in \$PATH."
        read -n 1
        return
    fi

    # `mapfile` will not work with bash under 5.
    mapfile -t required_dependencies < <(awk -F ":" '/^[^#]/ { print $1 }' < "$SHELL_REQUIREMENTS" | sort -n | uniq)
    if [[ -z "${required_dependencies[*]}" ]]; then
        echo "Couldn't load required dependencies from $SHELL_REQUIREMENTS ?!"
        echo "Will not install dependencies."
        return
    fi

    if [[ -z "$(command -v pkcon)" ]]; then
        1>&2 echo "PackageKit is required in order to install login shell packages. Exiting."
        return
    fi
    
    echo -e "Installing essential shell packages: \033[38;5;39m"
    echo -n "${required_dependencies[*]}"
    echo -e "\033[0m"

    pkcon install --allow-reinstall "${required_dependencies[@]}"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && require-login-shell-packages "$@"
