#!/usr/bin/env bash

# HELP check if the type of the pc running is a desktop

_depends-on dmidecode || exit

is-desktop-type () (
    _echo-debug "is-desktop-type $(sudo dmidecode --string chassis-type)"
    [[ "$(sudo dmidecode --string chassis-type)" == "Desktop" ]] && return 0
    return 1
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-desktop-type "$@"
