#!/usr/bin/env bash

# HELP check if the computer running the script is a mobile type (e.g. laptop)

is-mobile-type () (
    _echo-debug "is-mobile-type $(sudo dmidecode --string chassis-type)"
    readonly CHASSIS_TYPE="$(sudo dmidecode --string chassis-type)"
    [[ $CHASSIS_TYPE == "Notebook" || $CHASSIS_TYPE == "Tablet" || $CHASSIS_TYPE == "Convertible" ]] && return 0
    return 1
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-mobile-type "$@"
