#!/usr/bin/env bash

# HELP check if service $1 is running

is-service-running () {
    _echo-debug "is-service-running $1"
    [[ $# != 1 ]] && exit 1
    systemctl is-active --quiet "$1" && return 0
    return 1
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-service-running "$@"
