#!/usr/bin/env bash

# HELP check if homefs is btrfs

_depends-on stat || exit

is-btrfs-homefs () (
    home_fs=$(stat -f --format=%T "$(eval echo "~${SUDO_USER:-$(whoami)}")")
    _echo-debug "is-btrfs-homefs $home_fs"
    [[ "btrfs" == $home_fs ]] && return 0
    return 1
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && is-btrfs-homefs "$@"
