#!/usr/bin/env bash

# HELP get the nvidia gpu model

_depends-on lspci || exit

get-nvidia-gpu-model () (
    mdl="$(lspci | grep -i vga | grep NVIDIA | grep -E --only-matching "(\[.+\])" | tr -d '[]')" || exit
    echo "$mdl"
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && get-nvidia-gpu-model "$@"
