#!/usr/bin/env bash

# HELP adb-get-packages-named "id" "package.name"; find package for phone id

_depends-on adb || exit

adb-get-packages-named () (
    if [[ $# != 2 ]]; then echo "id, package-filter arguments must be given!"; exit 1; fi
    adb -s $1 shell cmd package list packages | cut -c 9- | xargs
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-get-packages-named $@
