#!/usr/bin/env bash

# HELP toggle screen on-off

_depends-on adb || exit

adb-toggle-screen () (
    adb shell input keyevent KEYCODE_POWER
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-toggle-screen
