#!/usr/bin/env bash

# HELP adb-clear-caches "id" "package.name"; clear package for phone id

_depends-on adb || exit

adb-clear-caches () (
    if [[ $# != 2 ]]; then echo "id, package arguments must be given!"; exit 1; fi
    adb -s $1 shell pm clear $2
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && adb-clear-caches $@
