#!/usr/bin/env -S python3 -S -OO

import sys


if sys.version_info.minor < 10:
    print(">= python3.10 required!", file=sys.stderr)
    sys.exit(1)


import os
import sys
import shlex
import time
import subprocess as sb

# HELP every <seconds> <command1> [<command2>] [<...>]; execute something ([command1:]) every seconds.

def every(interval_seconds, incantation: str | list[str]):
    print("Starting; exit via keyboard interrupt (Ctrl+C)...")
    while True:
        try:
            incantation = shlex.split(incantation) if isinstance(incantation, str) else incantation
            sb.Popen(
                incantation,
                cwd=os.getcwd(),
                env=os.environ.copy()
            )
            time.sleep(interval_seconds)
        except KeyboardInterrupt:
            print("Exiting via keyboard interrupt (Ctrl+C)...", file=sys.stderr)
            sys.exit(130)


if __name__ == "__main__":
    if len(sys.argv) < 3:
        sys.exit(2)

    try:
        every(int(sys.argv[1]), sys.argv[2:])
    except ValueError:
        print("First argument must be an integer >= 0!", file=sys.stderr)
        sys.exit(2)
    except FileNotFoundError as err:
        print(str(err), file=sys.stderr)
        sys.exit(1)
