#!/usr/bin/env bash

# HELP ffconvert-dnxhr-lb <file1> <file2> <...>; convert N video files to dnxhr lb

_depends-on ffmpeg || exit

# ffmpeg convert video file to dnxhr
ffconvert-dnxhr () (
    [[ -z "$*" ]] && return 2
    for arg in "$@"; do
        local output=$(basename -- "${arg%.*}")
        ffmpeg -i "$arg" -strict 'unofficial' -c:v dnxhd -profile:v dnxhr_lb -pix_fmt yuv422p -c:a pcm_s16le "$PWD/$output-converted.lb.mxf" 1> /dev/null
        echo "Done $output-converted"
    done
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffconvert-dnxhr "$@"
