#!/usr/bin/env bash

# HELP ffconvert-mp4 <file1> <file2> <...>; convert N video files to mp4

_depends-on ffmpeg || exit

# ffmpeg convert video file to mp4
ffconvert-mp4 () (
    [[ -z "$*" ]] && return 2
    for arg in "$@"; do
        local output=$(basename -- "${arg%.*}")
        ffmpeg -i "$arg" -codec copy "$PWD/$output-converted.mp4" 1> /dev/null
        echo "Done $output-converted"
    done
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffconvert-mp4 "$@"
