#!/usr/bin/env bash

# HELP ffextract-frames-mp4 <path/to/file>; extract frames as uncompressed/raw screenshots (.bmp) to $CWD

_depends-on ffmpeg || exit

# ffmpeg extract frames
ffextract-frames-mp4 () (
    [[ -z "$*" ]] && return 2
    [[ "$#" -ne 1 ]] && return 2
    # $1 input
    output=$(basename -- "${1%.*}")
    ffmpeg -i "$1" "$PWD/$output%09d.bmp"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ffextract-frames-mp4 "$@"
