#!/usr/bin/env fish

# https://videoconverter.wondershare.com/sync-audio/ffmpeg-sync-audio-and-video.html
# HELP ffshift <right | left> <file.mp4> <milliseconds>; shift mp4's audio to the right or left

_depends-on ffmpeg || exit

function ffrshift
    ffmpeg -i "$argv[1]" -itsoffset "00:00:0$argv[2]" -i "$argv[1]" -vcodec copy -acodec copy -map 0:1 -map 1:0 "$output-shift.mp4"
end

function fflshift
    ffmpeg -i "$argv[1]" -itsoffset "00:00:0$argv[2]" -i "$argv[1]" -vcodec copy -acodec copy -map 1:0 -map 0:1 "$output-shift.mp4"
end

if [ "$_" != source ]
    if [ (count $argv) -ne 3 ]
        echo "Incorrect parameters."
        return 2
    end
    # convert millis format (int) to 0.0 format
    set seconds_millis $(math "$argv[3] / 1000")
    set output $(path change-extension '' $argv[2])
    if [ $argv[1] = "right" ]
        ffrshift $argv[2] $seconds_millis
        exit
    else if [ $argv[1] = "left" ]
        fflshift $argv[2] $seconds_millis
        exit
    end
    echo "usage: ffshift <right | left> <file.mp4> <milliseconds>"
    exit 2
end
