#!/usr/bin/env ruby

# HELP functionz [<name>]; list all available utility functions, optionally list only a specific doc

def echo_help_text(path)
    tail = File.basename(path)
    found = false
    File.open(path, "r") do |file|
        regexr_match = file.find { |line| line =~ /#\sHELP\s(.+)/ }
        found = !regexr_match.to_s.strip.empty?
        found ? puts("\033[0;31m%s\033[0m -> %s" % [tail, $1]) : nil
    end
    found ? nil : puts("\033[0;31m%s\033[0m" % tail)
end

# ruby is an unholy language
#  im torn, i do not know if this is disgusting or really cool
def dir_contents(dir)
    files = Dir.entries(File.dirname(dir)).sort().select{ |fn| ! fn.include? "."}
    for fn in files do
        path = "%s/%s" % [File.dirname(dir), fn]
        next unless File.file?(path)
        echo_help_text(path)
    end
end

if __FILE__ == $0
    if ARGV.length > 1
      puts "functionz [<name>]; list all available utility functions, optionally list only a specific doc"
      exit(2)
    end

    if ARGV.length == 1
        # glob the argument and return all matches
        globbed_path = Dir.glob("%s/*%s*" % [File.dirname(__FILE__), ARGV[0]])
        if globbed_path.empty?
            abort("Function '%s' does not exist!" % [ ARGV[0] ])
            exit(1)
        end

        globbed_path.each do |fn|
            echo_help_text(fn)
        end
        exit()
    end
    dir_contents(__FILE__)
end
