#!/usr/bin/env bash

# HELP git backup <destination directory>; backup current changes in a new directory
# "You can also add new commands by adding an executable file named git-newcommand to your PATH."

__git-backup () (
    mkdir -p "$1" || exit
    IFS=$'\n'
    for file in $(git status --porcelain); do
      fn="$(echo "$file" | awk '{ printf $2 }')"
      echo "Will backup '$fn' to '$1/$(dirname "$fn")'"
      mkdir -p "$1/$(dirname "$fn")"
      cp "$fn" "$1/$fn"
    done
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && __git-backup "$@"
