#!/usr/bin/env bash

# HELP git when <parent-head>; fzf-powered 'when' command to search when a particular commit was made
# "You can also add new commands by adding an executable file named git-newcommand to your PATH."

_depends-on fzf || exit

# code from here: https://gist.github.com/junegunn/f4fca918e937e6bf5bad
#  provided as 'fshow' fn.
# nothing was modified - everything taken as-is from the last iteration
#  of this gist.

__git-when() {
    git log --pretty=format:"%C(yellow)%h %C(reset)%C(yellow)%ad%C(auto)%d %s %C(blue)[%cn]" \
            --decorate \
            --date=short \
            --graph \
            --color=always |
    fzf -q "$*" \
        --ansi \
        --no-sort \
        --reverse \
        --tiebreak=index \
        --bind=ctrl-s:toggle-sort \
        --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && __git-when "$@"
