#!/usr/bin/env bash

# HELP git w --help; git wrapper for fzf-powered log commands.
# "You can also add new commands by adding an executable file named git-newcommand to your PATH."

_depends-on fzf || exit

show-usage () {
    echo "Usage: git wrapper for fzf-powered log commands.
       git w when <query>           # fzf-powered search for when a commit was made; query is passed as the initial fzf filter
       git w ls <git log arguments> # fzf-powered git log viewer; arguments are forwarded directly to git log"
}

# code from here: https://gist.github.com/junegunn/f4fca918e937e6bf5bad
#  provided as 'fshow' fn.

git-w-when () (
    git log --pretty=format:"%C(yellow)%h %C(reset)%C(yellow)%ad%C(auto)%d %s %C(blue)[%cn]" \
            --decorate \
            --date=short \
            --graph \
            --color=always |
    fzf -q "$*" \
        --ansi \
        --no-sort \
        --reverse \
        --tiebreak=index \
        --bind=ctrl-s:toggle-sort \
        --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
)

git-w-ls () (
    git log --pretty=format:"%C(yellow)%h %C(reset)%C(yellow)%ad%C(auto)%d %s %C(blue)[%cn]" \
            --decorate \
            --date=short \
            --graph \
            --color=always \
            "$@" |
    fzf \
        --ansi \
        --no-sort \
        --reverse \
        --tiebreak=index \
        --bind=ctrl-s:toggle-sort \
        --bind "ctrl-m:execute:
                (grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
                {}
FZF-EOF"
)

main () (
    subcommand="$1"
    subcommand_args=( "${@:2}" )
    case "$subcommand" in
        -h|--help)
            show-usage
            exit 0
            ;;
        when)
            git-w-when "${subcommand_args[@]}"
            ;;
        ls)
            git-w-ls "${subcommand_args[@]}"
            ;;
        *)
            echo "Unknown subcommand: ${subcommand:=NONE PROVIDED}"
            show-usage
            exit 2
            ;;
    esac
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"