#!/usr/bin/env bash

# HELP highlight (not filter) text with grep

highlight () (
    [[ -z "$*" ]] && return 2

    grep --color=always -iE "$1|\$"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && highlight "$@"