#!/usr/bin/env bash

# HELP a helix 'search' function, using 'ripgrep' and 'fzf'.

if test -z "$(command -v _depends-on)"; then 
    echo '_depends-on doesnt exist! are functionz loaded? exiting...' 1>&2
    exit 1
fi

# hx, fzf and ripgrep required for this to work
_depends-on hx fzf rg

# this function is from this blog post
#  https://blog.setale.me/2022/12/27/Switching-to-Helix-My-Experience-and-Tips/
#  all rights to the original author 
hxs() {
    RG_PREFIX="rg -i --files-with-matches"
    local files
    files="$(
    FZF_DEFAULT_COMMAND_DEFAULT_COMMAND="$RG_PREFIX '$1'" \
        fzf --multi 3 --print0 --sort --preview="[[ ! -z {} ]] && rg --pretty --ignore-case --context 5 {q} {}" \
            --phony -i -q "$1" \
            --bind "change:reload:$RG_PREFIX {q}" \
            --preview-window="70%:wrap" \
            --bind 'ctrl-a:select-all'
    )"
    # do NOT quote the vsplit, let it split the arguments instead
    [[ "$files" ]] && hx --vsplit $(echo "$files" | tr '\0' " ")
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && hxs "$@"
