#!/usr/bin/env bash

# HELP a helix 'search' function, using 'ripgrep' and 'fzf'.

if test -z "$(command -v _depends-on)"; then 
    echo '_depends-on doesnt exist! are functionz loaded? exiting...' 1>&2
    exit 1
fi

# hx, fzf and ripgrep required for this to work
_depends-on hx fzf rg

# this function is from this blog post
#  https://blog.setale.me/2022/12/27/Switching-to-Helix-My-Experience-and-Tips/
#  all rights to the original author 
_hxs () (
    RG_PREFIX="rg -i --files-with-matches"
    while :; do
        PREVIEW_WINDOW='--preview-window=0%:wrap'
        if [[ $(tput cols) -gt 80 ]]; then
            PREVIEW_WINDOW='--preview-window=70%:wrap'
        fi
        file="$(
            FZF_DEFAULT_COMMAND_DEFAULT_COMMAND="$RG_PREFIX '$1'" \
                fzf --no-multi --sort --preview="[[ ! -z {} ]] && rg --pretty --smart-case --context 5 {q} {}" \
                    --phony -i -q "$1" \
                    --bind "change:reload:$RG_PREFIX {q}" \
                    $PREVIEW_WINDOW \
                    --bind 'ctrl-a:select-all' \
                2> /dev/null 
            )"
        # break only if there was an explicit EOF or keyboard interrupt in fzf
        test "$?" -eq 130 && break
        [[ -n "$file" ]] && hx "$file"
    done
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && _hxs "$@"
