#!/usr/bin/env bash

# HELP a spiritual reimplementation of GNU Stow, but simpler, for tinkerers.

# this is essentially an entry point to our dotfile setup;
#  this should be checked conditionally
if [[ -n $(command -v "_depends-on" ) ]]; then
    _depends-on curl python3 || exit
fi

pstow () {
    curl --tlsv1.2 -fsSL "https://raw.githubusercontent.com/gerelef/pstow/master/pstow.py" | python3 - --verbose "$@"
}

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && pstow "$@"
