#!/usr/bin/env bash

# HELP restart NetworkManager.service

restart-network-manager () (
    sudo systemctl restart NetworkManager.service
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && restart-network-manager
