#!/usr/bin/env bash

# HELP restart pipewire service

restart-pipewire () (
    systemctl --user restart pipewire
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && restart-pipewire