#!/usr/bin/env bash

# HELP rpmbuild & friends wrapper for common usecases

show-usage () {
    echo "Usage: rpm utility wrapper for common usecases.
        rpmutils buildrequires <spec file>  # will install all BuildRequires
	rpmutils build-copr <spec file> # will reproduce a copr build with network access locally, will automatically grab dependencies & sources
	rpmutils build <spec-file> # will reproduce a copr build with network access locally, will automatically grab sources & SKIP dependencies"
}

install-build-requires () (
    if ! test -f "$1"; then
        echo "spec file provided '$1' CANNOT be found!"
        exit 1
    fi
    pkexec sudo dnf builddep -y "$1"
)

build-copr () (
    if ! test -f "$1"; then
        echo "spec file provided '$1' CANNOT be found!"
	exit 1
    fi
    spectool -g -R "$1"
    pkexec sudo dnf builddep -y "$1"
    rpmbuild -ba -vv "$1" 
)

build () (
    if ! test -f "$1"; then
        echo "spec file provided '$1' CANNOT be found!"
	exit 1
    fi

    spectool -g -R "$1"
    rpmbuild -ba -vv "$1"
)

main () (
    arg="$1"
    case "$arg" in
        -h|--help)
            show-usage
            exit 0
            ;;
        buildrequires)
            install-build-requires "${@:2}"
            exit
            ;;
        build-copr)
	    build-copr "${@:2}"
	    exit
	    ;;
        build) 
	    build "${@:2}"
	    exit
	    ;;
        *)
            echo "Unknown main argument: $arg"
            show-usage
            exit 2
            ;;
    esac
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
