#!/usr/bin/env bash

# HELP rpmbuild & friends wrapper for common usecases

show-usage () {
    echo "Usage: rpm utility wrapper for common usecases.
       rpmw buildrequires <spec file>  # will install all BuildRequires
       rpmw build-copr <spec file> # will reproduce a copr build with network access locally, will automatically grab dependencies & sources
       rpmw build <spec-file> # will reproduce a copr build with network access locally, will automatically grab sources & SKIP dependencies
       rpmw bump <rpmdev-bumpspec args> # bumps release tags in specfiles
       rpmw depends-on <executable>  # check what are the direct dependencies of an executable that's CURRENTLY RUNNING via PID
       rpmw resolve-dep <file>  # check what package a file comes from (rpm -qf)
       rpmw compare-versions <version1> <version2>  # compare two versions to determine which one is larger than the other one"
}

install-build-requires () (
    if ! test -f "$1"; then
        echo "spec file provided '$1' CANNOT be found!"
        exit 1
    fi
    sudo dnf builddep -y --allowerasing "$1"
)

build-copr () (
    if ! test -f "$1"; then
        echo "spec file provided '$1' CANNOT be found!"
      	exit 1
    fi
    rm -r "$HOME/rpmbuild/SOURCES/"
    spectool -g -R "$1"
    sudo dnf builddep -y "$1"
    rpmbuild -ba -vv "$1"
)

build () (
    if ! test -f "$1"; then
        echo "spec file provided '$1' CANNOT be found!"
        exit 1
    fi

    spectool -g -R "$1"
    rpmbuild -ba -vv "$1"
)

bump () (
    rpmdev-bumpspec "$@"
)

depends-on () (
    pid=$(pidof $1)
    if [[ -z "$pid" ]]; then
        echo "Couldn't resolve pid of "
    fi

    lsof -P -T -p $pid
)

resolve-dep () (
    rpm -qf $1
)

compare-versions () (
    if [[ $# -ne 2 ]]; then
        echo "incorrect number of arguments to compare versions (got $#, expected 2)"
        show-usage
        exit 2
    fi

    rpmdev-vercmp "$1" "$2"
)

main () (
    arg="$1"
    case "$arg" in
        -h|--help)
            show-usage
            exit 0
            ;;
        buildrequires)
            install-build-requires "${@:2}"
            exit
            ;;
        build-copr)
    	    build-copr "${@:2}"
    	    exit
            ;;
        build)
    	    build "${@:2}"
    	    exit
            ;;
        bump)
    	    bump "${@:2}"
    	    exit
            ;;
        depends-on)
    	    depends-on "${@:2}"
    	    exit
            ;;
        resolve-dep)
    	    resolve-dep "${@:2}"
    	    exit
            ;;
        compare-versions)
            compare-versions "${@:2}"
            exit
            ;;
        *)
            echo "Unknown main argument: $arg"
            show-usage
            exit 2
            ;;
    esac
)

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
