#!/usr/bin/env bash

# HELP dump all profile spotify playlists to a file; the filename is echoed to stdout.

_depends-on curl jq || exit

curl-bearer-token () (
    curl -sS --dump-header - -b "" -X GET "https://open.spotify.com/" | grep --only-matching --extended-regexp '"accessToken":".+","accessTokenExpirationTimestampMs' | sed -nr 's/"accessToken":"(.+)","accessTokenExpirationTimestampMs/\1/p' -
)

spotify-dump-public-playlist-uris-from-profile () (
    if [[ $# != 1 ]]; then
        echo "profile URI must be given!"
        exit 1
    fi
    filename_and_queries="$(basename $1))"
    profile_id="${filename_and_queries%?*}"
    bearer_header="Authorization: Bearer $(curl-bearer-token)"
    body="$(curl -sS -b "" -H "$bearer_header" -X GET "https://spclient.wg.spotify.com/user-profile-view/v3/profile/$profile_id/playlists?offset=0&limit=200")"
    echo "$body" | jq '.public_playlists[].uri' | tr -d '"' | awk -F ':' '{ print $3 }' > "$profile_id"
    echo "$profile_id"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && spotify-dump-public-playlist-uris-from-profile "$@"
