#!/usr/bin/env bash

# HELP flush /swapfile; DANGEROUS, will NOT check if /swapfile contents fit in memory!

swap_used="$(free -m | awk '/Swap:/{ print $3 }')"

_depends-on free awk grep swapon swapoff || exit

if [[ -z "$swap_used" ]]; then
    echo "FATAL ERROR: SWAP USED IS EMPTY: $swap_used, CANNOT CONTINUE!" 1>&2
    exit 1
fi

if ! [ "$swap_used" -eq "$swap_used" ] 2>/dev/null; then
    echo "FATAL ERROR: SWAP USED IS NON-NUMERIC: $swap_used, CANNOT CONTINUE!" 1>&2
    exit 1
fi

if [[ "$swap_used" -eq 0 ]]; then
    echo "Current usage @ $swap_used MB, no need to flush, exiting early..." 1>&2
    exit 0
fi

memory_available="$(free -m | awk '/Mem:/{ print $NF }')"

if [[ -z "$memory_available" ]]; then
    echo "FATAL ERROR: MEMORY AVAILABLE IS EMPTY: $memory_available, CANNOT CONTINUE!" 1>&2
    exit 1
fi

if ! [ "$memory_available" -eq "$memory_available" ] 2>/dev/null; then
    echo "FATAL ERROR: MEMORY AVAILABLE IS NON-NUMERIC: $memory_available, CANNOT CONTINUE!" 1>&2
    exit 1
fi

if [[ $swap_used -ge $memory_available ]]; then
    echo "FATAL ERROR: NOT ENOUGH AVAILABLE MEMORY TO MOVE TO FROM SWAP; CURRENT SWAP USED IS $swap_used and $memory_available IS AVAILABLE." 1>&2
    exit 1
fi

echo "Current usage @ $swap_used MB, turning swap off temporarily to flush contents..."
SUPRESSED="$(sudo sudo --help)"

sudo swapoff -a &
while [[ $swap_used -ge 1 ]]; do
    echo "Current usage @ $swap_used MB"
    sleep .5
    swap_used=$(free -m | awk '{ print $1 " " $3 }' | grep -i 'swap' | awk '{ print $2 }')
done

echo "Current usage @ $swap_used MB, turning back on..."
sleep .5
sudo swapon -a

echo "Done."
