#!/usr/bin/env bash

# HELP flush /swapfile; DANGEROUS, will NOT check if /swapfile contents fit in memory!

# TODO add check if swap_used is more than the Mem: total - used via `free -m`

swap_used=$(free -m | awk '{ print $1 " " $3 }' | grep -i 'swap' | awk '{ print $2 }')

_depends-on free awk grep swapon swapoff || exit

if [[ -z "$swap_used" ]]; then
    echo "FATAL ERROR: USAGE VARIABLE IS EMPTY: $swap_used, CANNOT CONTINUE!"
    exit 1
fi

if ! [ "$swap_used" -eq "$swap_used" ] 2>/dev/null; then
    echo "FATAL ERROR: USAGE VARIABLE IS NON-NUMERIC: $swap_used, CANNOT CONTINUE!"
    exit 1
fi

if [[ "$swap_used" -eq 0 ]]; then
    echo "Current usage @ $swap_used MB, no need to flush, exiting early..."
    exit 0
fi

echo "Current usage @ $swap_used MB, turning swap off temporarily to flush contents..."
SUPRESSED="$(sudo sudo --help)"

sudo swapoff -a &
while [[ $swap_used -ge 1 ]]; do
    echo "Current usage @ $swap_used MB"
    sleep .5
    swap_used=$(free -m | awk '{ print $1 " " $3 }' | grep -i 'swap' | awk '{ print $2 }')
done

echo "Current usage @ $swap_used MB, turning back on..."
sleep .5
sudo swapon -a

echo "Done."
