#!/usr/bin/env bash

# HELP update package manager; update flatpak; update snap; update selenium-manager; update npm

update-everything () (
    echo "$(tput bold)$(tput setaf 6)──── Updating w/ package manager ────$(tput sgr0)"
    # the reason this for loop exists is to act as a "block", so we can break control flow
    #  when we're done updating platform packages (since there will be only 1 package manager per sys)
    while :; do
        if [[ -n "$(command -v pkcon)" ]]; then
            # this will error if there are no packages, that's fine
            pkcon update --noninteractive  
            break
        fi

        echo "No package manager found!"
        echo "Supported package managers per platform:"
        echo -e "\e[1;38;05;220mLinux:\e[0m  PackageKit"
        echo -e "\e[1;38;05;220mmacOS:\e[0m  Unsupported."
        echo -e "\e[1;38;05;220mCygwin:\e[0m Unsupported."
        break
    done

    if [[ -n "$(command -v flatpak)" ]]; then
        echo "$(tput bold)$(tput setaf 6)──── Updating flatpak ────$(tput sgr0)"
        flatpak update -y || exit
        flatpak uninstall --unused -y || exit
    fi

    if [[ -n "$(command -v snap)" ]]; then
        echo "$(tput bold)$(tput setaf 6)──── Updating snap ────$(tput sgr0)"
        if ! snap refresh; then
            echo "Snap failed to update w/ sudoless permissions."
            echo "Please configure policykit to allow this kind of action."
        fi
    fi

    if [[ -n "$(command -v selenium-manager)" ]]; then
        echo "$(tput bold)$(tput setaf 6)──── Updating chromedriver ────$(tput sgr0)"
        # no exit here; we might error since this often gets drivers from file-sharing hosts (e.g. google-drive)
        selenium-manager --debug --browser chrome
    fi

    if [[ -n "$(command -v npm)" ]]; then
        echo "$(tput bold)$(tput setaf 6)──── Updating npm ────$(tput sgr0)"
        sudo npm install -g npm@latest || exit
    fi

    # this is bad but it's the official 'packaging' format jesus christ
    if [[ -f "$HOME/.joplin/Joplin.AppImage" ]]; then
        curl --proto '=https' --tlsv1.2 -sSf 'https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh' | bash
    fi
    return 0
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && update-everything "$@"
