#!/usr/bin/env bash

# HELP download a thumbnail

_depends-on yt-dlp || exit

ytdl-thumbnail () (
    [[ -z "$*" ]] && return 2

    yt-dlp --write-thumbnail --skip-download "$@"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ytdl-thumbnail "$@"
