#!/usr/bin/env bash

# HELP download eng subs from video

_depends-on yt-dlp || exit

ytdl-subs () (
    [[ -z "$*" ]] && return 2

    yt-dlp --skip-download --write-subs --sub-lang en --sub-format ttml "$@"
)

# run only if this file is not sourced
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && ytdl-subs "$@"
