theme = "transparent"

[editor]
bufferline = "multiple"
completion-replace = true
popup-border = "all"
end-of-line-diagnostics = "hint"
auto-format = false

[editor.inline-diagnostics]
cursor-line = "error"

[editor.indent-guides]
render = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
newline = "all"

[editor.file-picker]
hidden = false

[keys.select]
end = "goto_line_end_newline"
